// Generates lib/core/localization/api_errors.g.dart from the dashboard's catalogue.
//
//   node tool/generate_api_errors.mjs
//
// The backend answers in English (installed app versions match some messages
// verbatim), and the dashboard keeps the one catalogue that translates every
// message it can throw: the rules in src/utils/apiError.ts and the copy in
// src/i18n/locales/api-errors.{it,en}.json. The app reuses that catalogue
// instead of keeping a second one that would drift. Re-run this after adding a
// backend message to the dashboard.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, '..');
const dashboard = path.resolve(app, '../vyzi-dashboard');
const ts = createRequire(path.join(dashboard, 'package.json'))('typescript');

const source = fs.readFileSync(path.join(dashboard, 'src/utils/apiError.ts'), 'utf8');
const ast = ts.createSourceFile('apiError.ts', source, ts.ScriptTarget.Latest, true);
const catalogue = (lang) =>
  JSON.parse(fs.readFileSync(path.join(dashboard, `src/i18n/locales/api-errors.${lang}.json`), 'utf8'));

/** A Dart string literal. */
const dart = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n')}'`;

/** A Dart raw string for a regex source, falling back to an escaped one. */
const dartPattern = (s) => {
  if (!s.includes("'")) return `r'${s}'`;
  if (!s.includes('"')) return `r"${s}"`;
  return dart(s);
};

const objectOf = (name) => {
  let found;
  (function visit(n) {
    if (ts.isVariableDeclaration(n) && n.name.getText(ast) === name) found = n.initializer;
    ts.forEachChild(n, visit);
  })(ast);
  if (!found) throw new Error(`apiError.ts has no ${name}`);
  return found;
};

const text = (node) => {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
  throw new Error(`not a string literal: ${node.getText(ast)}`);
};

const rules = objectOf('rules').elements.map((element) => {
  const props = Object.fromEntries(element.properties.map((p) => [p.name.getText(ast), p.initializer]));
  const params = props.params
    ? Object.fromEntries(props.params.properties.map((p) => [p.name.getText(ast), text(p.initializer)]))
    : {};
  const match = props.match;
  if (match.kind === ts.SyntaxKind.RegularExpressionLiteral) {
    const literal = match.getText(ast);
    const slash = literal.lastIndexOf('/');
    return { pattern: literal.slice(1, slash), flags: literal.slice(slash + 1), key: text(props.key), params };
  }
  return { exact: text(match), key: text(props.key), params };
});

const record = (name) =>
  Object.fromEntries(objectOf(name).properties.map((p) => [p.name.getText(ast).replace(/^"|"$/g, ''), text(p.initializer)]));
const errorCodes = record('errorCodes');
const billStatusByLabel = record('billStatusByLabel');

/** Flattens the catalogue and turns i18next `{{name}}` into GetX-style `@name`. */
const flatten = (obj, prefix = '', out = {}) => {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'string') out[key] = v.replace(/{{\s*(\w+)\s*}}/g, '@$1');
    else flatten(v, key, out);
  }
  return out;
};

const map = (entries) => entries.map(([k, v]) => `  ${dart(k)}: ${dart(v)},`).join('\n');
const params = (p) => `{${Object.entries(p).map(([k, v]) => `${dart(k)}: ${dart(v)}`).join(', ')}}`;
const rule = (r) =>
  r.exact !== undefined
    ? `  ApiErrorRule.exact(${dart(r.exact)}, ${dart(r.key)}${Object.keys(r.params).length ? `, params: ${params(r.params)}` : ''}),`
    : `  ApiErrorRule.pattern(RegExp(${dartPattern(r.pattern)}${r.flags.includes('i') ? ', caseSensitive: false' : ''}), ${dart(r.key)}${Object.keys(r.params).length ? `, params: ${params(r.params)}` : ''}),`;

const out = `// GENERATED by tool/generate_api_errors.mjs from the dashboard's
// src/utils/apiError.ts and src/i18n/locales/api-errors.*.json. Do not edit by
// hand: add the backend message to the dashboard catalogue and re-run it.
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars

/// One backend message and the catalogue key it translates to. [params] names
/// the capture groups whose value is itself translated: \`value\`, \`list\` or
/// \`billStatus\`.
class ApiErrorRule {
  final String? exact;
  final RegExp? pattern;
  final String key;
  final Map<String, String> params;

  ApiErrorRule.exact(String this.exact, this.key, {this.params = const {}})
      : pattern = null;
  ApiErrorRule.pattern(RegExp this.pattern, this.key, {this.params = const {}})
      : exact = null;
}

/// In match order: the first rule that fits wins.
final List<ApiErrorRule> apiErrorRules = [
${rules.map(rule).join('\n')}
];

/// Backend \`errorCode\`s that pin the message regardless of its wording.
const Map<String, String> apiErrorCodes = {
${map(Object.entries(errorCodes))}
};

/// English bill-status labels the backend writes into messages.
const Map<String, String> apiErrorBillStatus = {
${map(Object.entries(billStatusByLabel))}
};

const Map<String, String> apiErrorsIt = {
${map(Object.entries(flatten(catalogue('it'))))}
};

const Map<String, String> apiErrorsEn = {
${map(Object.entries(flatten(catalogue('en'))))}
};
`;

const target = path.join(app, 'lib/core/localization/api_errors.g.dart');
fs.writeFileSync(target, out);
console.log(`${rules.length} rules, ${Object.keys(errorCodes).length} error codes -> ${path.relative(app, target)}`);
