final Map<String, String> enUS = {
  // ==================== AUTH FLOW ====================
  'auth.login.title': 'Sign in to your account',
  'auth.login.email_label': 'Email Address *',
  'auth.login.email_hint': 'Enter your email address',
  'auth.login.email_error': 'Please enter a valid email',
  'auth.login.password_label': 'Password *',
  'auth.login.password_hint': '••••••••••',
  'auth.login.password_error': 'Minimum 8 characters',
  'auth.login.forgot_password': 'Forgot your password?',
  'auth.login.reset_now': 'Reset now',
  'auth.login.button': 'Sign in',
  'auth.login.divider': 'Or sign in with',
  'auth.login.facebook': 'Sign in with Facebook',
  'auth.login.apple': 'Sign in with Apple',
  'auth.login.google': 'Sign in with Google',
  'auth.login.no_account': 'Don\'t have an account?',
  'auth.login.signup': 'Sign up now',
  'auth.login.error.failed': 'Login failed. Please try again.',
  'auth.login.error.invalid_credentials': 'Invalid email or password',
  'auth.login.error.suspended': 'Your account has been suspended. Contact support.',
  'auth.login.error.not_verified': 'Email not verified. Complete OTP verification.',
  'auth.login.error.social_failed': 'Social login failed. Please try again.',
  'auth.login.error.no_social_account':
      'No account yet for this profile. Choose your account type to sign up.',

  // Social sign-in (Google / Facebook / Apple)
  'auth.social.error.cancelled': 'Sign-in cancelled.',
  'auth.social.error.generic': 'Social login failed. Please try again.',
  'auth.social.error.interrupted': 'Sign-in was interrupted. Please try again.',
  'auth.social.error.configuration':
      'Social sign-in is unavailable: invalid configuration. Please contact support.',
  'auth.social.error.no_firebase_token':
      'Could not obtain the authentication token. Please try again.',
  'auth.social.error.account_exists':
      'An account with this email already exists, registered with a different sign-in method.',
  'auth.social.error.provider_disabled':
      'This sign-in method is not enabled. Please contact support.',
  'auth.social.error.user_disabled': 'This account has been disabled.',
  'auth.social.error.network':
      'No connection. Check your network and try again.',

  'auth.signup.title': 'Create an account',
  'auth.signup.first_name_label': 'First Name *',
  'auth.signup.first_name_hint': 'Enter your first name',
  'auth.signup.last_name_label': 'Last Name *',
  'auth.signup.last_name_hint': 'Enter your last name',
  'auth.signup.email_label': 'Email Address *',
  'auth.signup.email_hint': 'Enter your email address',
  // A business account is registered with its PEC. Nothing here can tell a
  // certified address from an ordinary one - the two are identical strings -
  // so the label is what tells the company which of the two to type.
  'auth.signup.phone_label': 'Phone Number (optional)',
  'auth.signup.company_name_label': 'Company Name *',
  'auth.signup.company_name_hint': 'Enter your company name',
  'auth.signup.company_name_error': 'Company name is required',
  'auth.signup.company_name_short': 'Company name is too short',
  'auth.signup.vat_label': 'VAT Number *',
  'auth.signup.vat_hint': '11 digits, no spaces',
  'auth.signup.vat_required': 'VAT number is required',
  'auth.signup.vat_invalid': 'Enter a valid VAT number — 11 digits, and the last one must match the rest.',
  'auth.signup.password_label': 'Password *',
  'auth.signup.password_hint': '••••••••••',
  'auth.signup.password_lowercase': 'Must contain at least one lowercase letter',
  'auth.signup.password_uppercase': 'Must contain at least one uppercase letter',
  'auth.signup.password_number': 'Must contain at least one number',
  'auth.signup.password_special': 'Must contain at least one special character',
  'auth.signup.confirm_password_label': 'Confirm Password *',
  'auth.signup.confirm_password_hint': '••••••••••',
  'auth.signup.password_mismatch': 'Passwords do not match',
  'auth.signup.accept_prefix': 'I accept the ',
  'auth.signup.terms_link': 'Terms of Service',
  'auth.signup.privacy_link': 'Privacy Policy',
  'auth.signup.list_separator': ', ',
  'auth.signup.list_conjunction': ' and ',
  'auth.signup.terms_required': 'You must accept the Terms of Service and Privacy Policy to proceed.',
  'auth.signup.button': 'Sign up',
  'auth.signup.divider': 'Or sign in with',
  'auth.signup.have_account': 'Already have an account? ',
  'auth.signup.login': 'Sign in',
  'auth.signup.error.failed': 'Registration failed. Please try again.',
  'auth.signup.error.email_exists': 'Email already registered',
  'auth.signup.error.vat_exists': 'This VAT number is already registered to another account',

  'auth.otp.title': 'Verify code',
  'auth.otp.button': 'Verify code',
  'auth.otp.resend': 'Resend code',
  'auth.otp.error_incomplete': 'Enter the complete code',

  'auth.forgot_password.title': 'Forgot Password',
  'auth.forgot_password.email_label': 'Email Address *',
  'auth.forgot_password.email_hint': 'Enter your email address',
  'auth.forgot_password.email_error': 'Please enter a valid email',
  'auth.forgot_password.button': 'Send code',

  'auth.reset_password.title': 'Reset Password',
  'auth.reset_password.password_label': 'Password *',
  'auth.reset_password.password_hint': '••••••••••',
  'auth.reset_password.password_error': 'Minimum 6 characters',
  'auth.reset_password.confirm_label': 'Confirm Password *',
  'auth.reset_password.confirm_hint': '••••••••••',
  'auth.reset_password.mismatch': 'Passwords do not match',
  'auth.reset_password.button': 'Reset Password',

  'auth.success.title': 'All set!',
  'auth.success.message': 'Password updated\nsuccessfully',
  'auth.success.button': 'Back to login',

  // ==================== HOME SCREEN ====================
  'home.header.greeting': 'Hello, there! 👋',
  'home.header.subtitle': 'Ready to save on your utilities?',
  'home.header.onboarding_greeting': 'Hello, there! 👋',
  'home.header.onboarding_subtitle': 'Take control of your utilities today',
  'home.upload_section.title': 'Upload Your First\nBill',
  'home.upload_section.subtitle': 'Let us analyze your current plan\nand find better offers',
  'home.upload_section.button': 'Start Saving',
  'home.summary.savings_title': 'Potential savings',
  'home.summary.savings_subtitle': 'per year',
  'home.summary.utilities_title': 'Active utilities',
  'home.summary.utilities_subtitle': 'managed',
  'home.how_it_works.title': 'How It Works',
  'home.how_it_works.step1_title': 'Upload Your Bill',
  'home.how_it_works.step1_desc': 'Take a photo of your bill or upload a PDF directly from the app.',
  'home.how_it_works.step2_title': 'We Analyze and Propose',
  'home.how_it_works.step2_desc': 'The VYZI team analyzes your current situation. You\'ll receive a notification with the best offers.',
  'home.how_it_works.step3_title': 'Choose and Activate',
  'home.how_it_works.step3_desc': 'Compare the selected offers and choose your favorite. We handle the activation.',
  'home.utilities_section.title': 'Your Utilities',
  'home.utilities_section.view_all': 'View All',
  'home.utilities_section.address_missing': 'Address unavailable',
  'home.actions.title': 'What do you want to do today?',
  'home.actions.change_supplier': 'Switch supplier',
  'home.actions.change_supplier_desc': 'Compare offers and see if you could save.',
  'home.actions.transfer': 'Change account holder',
  'home.actions.transfer_desc': 'Change the account holder and supplier in one request.',
  'home.actions.activate': 'Activate a new utility',
  'home.actions.activate_desc': 'Request electricity or gas activation.',
  'home.actions.activate_badge': 'New',
  'home.actions.check_invoice': 'Check your bill',
  'home.actions.check_invoice_desc': 'Check whether your current offer is still competitive.',

  // ==================== PROFILE SCREEN ====================
  'profile.title': 'Profile',
  'profile.subtitle': 'Manage your account settings',
  'profile.account_type_personal': 'Personal',
  'profile.account_type_business': 'Business',
  'profile.section.account': 'Account Management',
  'profile.section.invite': 'Invite and Rewards',
  'profile.section.other': 'Other',
  'profile.menu.personal_data': 'Personal Data',
  'profile.menu.personal_data_desc': 'Edit your profile information',
  'profile.menu.utilities': 'Your utilities',
  'profile.menu.utilities_desc': 'View active services',
  'profile.menu.requests': 'Your requests',
  'profile.menu.requests_desc': 'Follow your switches',
  'profile.menu.invite': 'Invite and Earn',
  'profile.menu.invite_desc': 'Share your link and earn 10',
  'profile.menu.support': 'Support',
  'profile.menu.support_desc': 'Get help and contact us',
  'profile.menu.agreements': 'Agreements',
  'profile.menu.agreements_desc': 'Exclusive partner discounts',
  'profile.menu.more': 'More',
  'profile.menu.more_desc': 'Legal Privacy',
  'profile.menu.logout': 'Log out',
  'profile.logout.confirm': 'Are you sure you want to log out?',
  'profile.logout.cancel': 'Cancel',
  'profile.settings.privacy': 'Privacy Policy',
  'profile.settings.terms': 'Terms and Conditions',
  'profile.settings.about': 'About VYZI',
  'profile.settings.faq': 'FAQ',
  'profile.settings.language': 'Language',
  'profile.settings.language_italian': 'Italiano',
  'profile.settings.language_english': 'English',
  'profile.settings.delete_account': 'Delete Account',
  'profile.settings.delete_confirm_title': 'Delete Account',
  'profile.settings.delete_confirm_msg': 'Are you sure you want to delete your account? This action is irreversible.',
  'profile.settings.delete_confirm_cancel': 'Cancel',
  'profile.settings.delete_confirm_delete': 'Delete',
  'profile.settings.title': 'Settings',

  // ==================== SUPPORT SCREEN ====================
  'support.title': 'Support',
  'support.greeting': 'Hi, how can we help you?',
  'support.subtitle': 'Search our guides or contact technical support.',
  'support.form.tab.technical': 'Technical Support',
  'support.form.tab.billing': 'Billing and Payments',
  'support.form.topic_label': 'Topic',
  'support.form.message_label': 'Message',
  'support.form.message_hint': 'Describe your problem or question...',
  'support.form.submit': 'Submit Request',

  // ==================== NAVBAR ====================
  'navbar.home': 'Home',
  'navbar.utilities': 'Supplies',
  'navbar.request': 'Requests',
  'navbar.profile': 'Profile',

  // ==================== COMMON ====================
  'common.error': 'Error',
  'common.success': 'Success',
  'common.loading': 'Loading...',
  'common.no_data': 'No data available',
  'common.try_again': 'Try again',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.close': 'Close',
  'common.back': 'Back',
  'common.no_internet': 'No Internet Connection',
  'common.no_internet_message': 'No Internet connection. Please try again.',
  'common.oops': 'Oops!',
  'common.retry': 'Retry',
  'common.server_error': 'Server error',
  'common.unexpected_error': 'An unexpected error occurred',
  'common.failed_to_load': 'Failed to load data',
  'common.save': 'Save',
  'common.got_it': 'Got it',
  'common.per_month': '/month',

  // ==================== EMAIL BILL ====================
  'home.email_bill.confirm_same_email': 'Make sure you use the same email address you used to create your VYZI account.',
  'home.email_bill.note1': 'If you send photos of your bill, attach at least the first 3 pages.',
  'home.email_bill.note2': 'You can also send pricing terms or other documents useful for the analysis.',
  'home.email_bill.button': 'I have sent my bill',
  'home.email_bill.back': 'Go back',
  'home.email_bill.go_to_requests': 'Go to Requests',
  'home.email_bill.back_to_home': 'Back to Home',
  'home.email_bill.title': 'Send your bill by email',
  'home.email_bill.instructions': 'Instructions',
  'home.email_bill.instruction_text': 'You can send us your bill whenever you like by attaching it to an email to the address below.',
  'home.email_bill.email_label': 'Email address',
  'home.email_bill.copy': 'Copy',

  // ==================== BILLS ====================
  'bills.title': 'My Bills',
  'bills.load_failed': 'Failed to load bills',
  'bills.no_bills_found': 'No bills found',
  'bills.list.amount': 'Amount',
  'bills.list.period': 'Period',
  'bills.list.date': 'Date',
  'bills.detail.title': 'Bill details',
  'bills.detail.info': 'Bill Information',
  'bills.detail.contract_banner.ready_title': 'Contract Ready to Sign',
  'bills.detail.contract_banner.ready_subtitle': 'Tap to see how to sign your contract',
  'bills.detail.contract_banner.in_activation_title': 'Utility Being Activated',
  'bills.detail.contract_banner.in_activation_subtitle': 'Tap to see your switch details',
  'bills.detail.contract_banner.active_title': 'Contract Active',
  'bills.detail.contract_banner.active_subtitle': 'Tap to view your active service',
  'bills.detail.contract_banner.preparing_title': 'Contract Being Prepared',
  'bills.detail.contract_banner.preparing_subtitle': 'Tap to follow the progress',
  'bills.detail.verification_banner.title': 'Verification Required',
  'bills.detail.verification_banner.subtitle': 'Tap to send the requested documents',
  'case.document.banner.title': 'Document needs replacing',
  'case.document.banner.subtitle': 'Tap to upload a new one',
  'case.document.rejection.expired': 'Expired',
  'case.document.rejection.unreadable': 'Not readable',
  'case.document.rejection.incomplete': 'Incomplete',
  'case.document.rejection.wrong_document': 'Wrong document',
  'case.document.rejection.other': 'Not acceptable',
  'case.document.replace.title': 'New identity document',
  'case.document.replace.intro': 'We couldn\'t accept the document below. Upload a valid one and we\'ll review it again and let you know.',
  'case.document.replace.reason': 'Reason',
  'case.document.replace.submit': 'Send the new document',
  'case.document.replace.sent_title': 'Document sent',
  'case.document.replace.sent_body': 'We\'ll review it as soon as possible.',
  'bills.detail.recommended_offers': 'Recommended Offers',
  'bills.detail.progress.title': 'Progress',
  'bills.detail.progress.upload': 'Upload',
  'bills.detail.progress.verification': 'Verification',
  'bills.detail.progress.offers': 'Offers',
  'bills.detail.progress.contract': 'Contract',
  'bills.detail.progress.activation': 'In Activation',
  'bills.detail.progress.activated': 'Activated',
  'bills.detail.hero.done_title': 'Your Switch is Complete',
  'bills.detail.hero.done_desc': 'Your new supply is active. Nothing else is needed from you.',
  'bills.detail.hero.attention_title': 'This Request Needs Attention',
  'bills.detail.timeline.sent_title': 'Sent',
  'bills.detail.timeline.sent_subtitle': 'We have received your request.',
  'bills.detail.timeline.analyzed_title': 'Analyzed',
  'bills.detail.timeline.analyzed_subtitle': 'We have checked the details of your bill.',
  'bills.detail.timeline.contract_signed_title': 'Contract signed',
  'bills.detail.timeline.contract_signed_subtitle': 'The contract with your new supplier has been signed.',
  'bills.detail.timeline.in_activation_title': 'Activation in progress',
  'bills.detail.timeline.in_activation_subtitle': 'Your new supplier is completing the activation.',
  'bills.detail.timeline.activated_title': 'Activated',
  'bills.detail.timeline.activated_subtitle': 'Your new supply is active.',
  'bills.detail.timeline.ko_title': 'KO / Terminated',
  'bills.detail.timeline.ko_subtitle': 'This request was closed',

  // ==================== MY UTILITIES ====================
  'my_utility.title': 'Your utilities',
  'my_utility.subtitle': 'Manage your active utilities',
  'my_utility.upload_button': 'Upload your bill',
  'my_utility.no_utilities': 'No active utilities',
  'utility.pod_label': 'POD',
  'utility.active_since': 'Active Since',
  'utility.offer_type': 'Offer Type',
  'utility.address': 'Address',
  'utility.meter_number': 'Meter Number',
  'utility.send_email': 'Send Email',
  'utility.open_ticket': 'Open Ticket',
  'utility.open_ticket_desc': 'Get help via app support',
  'utility.website': 'Website',
  'utility.file_selected': 'File selected',
  'utility.scanned': 'Scanned',
  'utility.details_title': 'Utility Details',
  'utility.active_offer_badge': 'ACTIVE OFFER',
  'utility.status.activated': 'Active',
  'utility.status.awaiting_activation': 'In Activation',
  'utility.active_offer': 'Active Offer',
  'utility.offer_name': 'Offer Name',
  'utility.service_type': 'Service Type',
  'utility.supply_info': 'Supply Information',
  'utility.pod_code': 'POD CODE',
  'utility.copy': 'Copy',
  'utility.material_price': 'MATERIAL PRICE',
  // On a variable or indexed offer the figure beside this label is what the
  // customer pays on top of the market index, not the price of their energy.
  // The index keeps its market name (PUN, PSV) in both languages.
  'utility.spread_over_index': 'SPREAD OVER @index',
  'utility.activation': 'ACTIVATION',
  'utility.activation_planned': 'PLANNED ACTIVATION',
  'utility.annual_consumption': 'ANNUAL CONSUMPTION',
  'utility.fixed_fee': 'Fixed Fee',
  'utility.monthly_estimate': 'Monthly Estimate',
  'utility.contract_duration': 'Duration',
  'utility.expiry': 'Expiry',
  'utility.green_energy': 'Green Energy',
  'utility.contract_number': 'Contract Number',
  'utility.copied': 'Copied to clipboard',
  'utility.awaiting_activation_badge': 'IN ACTIVATION',
  'utility.error_load': 'We could not load this service.',
  'utility.retry': 'Retry',
  'utility.contact_support': 'Contact Support',
  'utility.about_supplier': 'About @name',
  'utility.faq': 'Frequently Asked Questions',

  // ==================== ONBOARDING ====================
  'onboarding.next': 'Next',
  'onboarding.skip': 'Skip',

  // ==================== REQUEST ====================
  'request.offers.load_failed': 'Failed to load offers',
  'request.bills.load_failed': 'Failed to load requests',
  'request.status.sent': 'Sent',
  'request.status.sent_desc': 'Request received successfully',
  'request.status.analyzing': 'Analysis in progress',
  'request.status.analyzing_desc': 'Our experts are verifying the data',
  'request.status.contract': 'Contract',
  'request.status.contract_desc': 'Final confirmation of the switch',
  'request.title': 'Requests',
  'request.go_to_details': 'View details and continue',
  'request.success.title': 'Request Sent Successfully',
  'request.success.subtitle': 'We have received your activation\nrequest.',
  'request.success.what_happens': 'What happens now',
  'request.success.step1': 'We verify the entered data',
  'request.success.step1_desc': 'Our automated systems verify the accuracy of your information.',
  'request.success.step2': 'We prepare the case',
  'request.success.step2_desc': 'We coordinate with service providers to start your request.',
  'request.success.step3': 'The contract will be available within 24 hours',
  'request.success.step3_desc': 'Your documentation will be generated and sent for signing.',
  'request.success.info_title': 'How will you complete the request?',
  'request.success.info_desc': 'You will receive instructions to sign the contract via SMS, email or dedicated link, depending on the chosen provider.',
  'request.success.view_request': 'View My Request',
  'request.success.back_home': 'Back to Home',
  'request.tab.your_offers': 'Your offers',
  'request.tab.my_requests': 'Your requests',

  // ==================== OFFER DETAILS ====================
  'offer.contract_term': 'Contract term',
  'offer.price_type': 'Price type',
  'offer.energy_price': 'Energy price',
  'offer.fixed_costs': 'Fixed energy supply costs',
  'offer.contract_duration': 'Contract duration',
  'offer.payment_method': 'Payment method',
  'offer.about_supplier': 'About the Supplier',

  // ==================== COMPLETE REQUEST FORM ====================
  'request.offer.green_energy': 'Green Energy',
  'request.offer.green_offer': 'Green Offer',
  'request.offer.annual_savings': 'Annual Savings',
  'request.form.readonly_summary': 'Read-only summary from Bill/Profile',
  'request.form.address_verified': 'Address verified',
  'request.form.delivery_address': 'Supply address',
  // The five fields collected for every address (supply, residence, shipping)
  'request.form.address': 'Address',
  'request.form.street_number': 'Street Number',
  'request.form.city': 'City',
  'request.form.postal_code': 'Postal Code',
  'request.form.province': 'Province',
  'request.form.new_residential_address': 'New Residential Address',
  'request.form.new_registered_office': 'New Registered Office',
  'request.form.payment_preference': 'Select how you prefer to pay',
  'request.form.choose_payment_method': 'Choose your payment method',
  'request.payment.sdd_title': 'Direct debit (SDD)',
  'request.payment.sdd_subtitle': 'Automatic payment from your bank account.',
  'request.payment.postal_bill_title': 'Postal payment slip',
  'request.payment.postal_bill_subtitle': 'You will receive a payment slip to pay your bill.',
  'request.form.holder_info': 'Holder information',
  'request.invoice.digital_title': 'Digital bill',
  'request.invoice.digital_subtitle': 'Receive your bill by email.',
  'request.invoice.paper_title': 'Paper bill',
  'request.invoice.paper_subtitle': 'Receive your bill by post.',
  'request.form.shipping_match_question': 'Does the shipping address match the delivery address?',
  'request.form.almost_done': 'Almost done!',
  'request.form.activate_offer': 'Activate Offer',
  'request.form.no_bill_warning': 'Please upload a bill first to activate this offer. Go to the Bills section to upload your energy bill.',
  'request.form.scan_document': 'Scan Document',
  'request.form.align_document': 'Align the document in the frame',
  'request.form.supported_formats': 'QR codes and barcodes are also supported',

  // ==================== SUPPORT CALLBACK ====================
  'support.callback.title': 'Request Callback',
  'support.callback.intro_text': 'We will call you at your preferred time to discuss your request.',
  'support.callback.phone_label': 'Phone Number',
  'support.callback.phone_hint': 'Enter your phone number',
  'support.callback.time_slot_label': 'Preferred Time Slot',
  'support.callback.select_time': 'Select a time',
  'support.callback.morning': 'Morning (09:00 – 12:00)',
  'support.callback.afternoon': 'Afternoon (12:00 – 15:00)',
  'support.callback.evening': 'Evening (15:00 – 18:00)',
  'support.callback.note': 'Note: Our team usually responds within 2-4 business hours on weekdays (Mon-Fri).',
  'support.callback.request_button': 'Request Callback',
  'support.other_contact_methods': 'Other ways to contact us',
  'support.default_topic': 'Billing Inquiry',

  // ==================== SUPPORT CATEGORIES ====================
  'support.getting_started': 'Getting Started',
  'support.getting_started_desc': 'Discover how to use the app step by step',
  'support.utilities_setup': 'Utilities Setup',
  'support.utilities_setup_desc': 'Manage the app and configure your utilities',
  'support.bills': 'Bills',
  'support.bills_desc': 'Upload and check your bills',
  'support.contact_us': 'Request assistance',
  'support.contact_us_desc': 'Open a ticket and get help',
  'support.my_requests': 'My Requests',
  'support.my_requests_desc': 'View your support request history',

  // ==================== SUPPORT FORM ====================
  'support.form.intro': 'Need help? Select a topic and describe your request. Our specialized team will respond as soon as possible.',
  'support.form.select_topic': 'Select a topic',
  'support.form.subject_label': 'Subject',
  'support.form.subject_hint': 'Brief description of your request...',
  'support.form.default_topic': 'Billing Inquiry',
  'support.form.topic.billing_question': 'Billing Question',
  'support.form.topic.technical_issue': 'Technical Issue',
  'support.form.topic.switching_process': 'Switching Process',
  'support.form.topic.contact_question': 'Contact Question',
  'support.form.topic.account_management': 'Account Management',
  'support.form.topic.other': 'Other',
  'support.form.validation.topic': 'Please select a topic',
  'support.form.validation.subject': 'Please enter a subject',
  'support.form.validation.message': 'Please enter a message',
  'support.form.success': 'Your request has been submitted successfully!',
  'support.form.success_title': 'Request Sent!',
  'support.form.success_subtitle': 'We\'ve received your message and will respond within 24 hours.',
  'support.form.error': 'Failed to submit request. Please try again.',
  'support.featured_label': 'FEATURED ARTICLE',
  'support.featured_title': '5 tips to reduce your bill by 20%',
  'support.contact.phone_label': 'Phone',
  'support.contact.email_label': 'Email',
  'support.contact.hours_label': 'Hours',
  'support.contact.hours_value': 'Mon-Fri, 09:00 – 18:00',

  // ==================== SUPPORT TICKETS ====================
  'support.tickets.empty': 'No support requests yet',
  'support.tickets.status.open': 'Open',
  'support.tickets.status.in_progress': 'In Progress',
  'support.tickets.status.resolved': 'Resolved',
  'support.tickets.status.closed': 'Closed',
  'support.ticket_detail.title': 'Ticket Detail',
  'support.ticket_detail.send_hint': 'Type a message...',
  'support.ticket_detail.closed_notice': 'This ticket has been closed and no longer accepts messages.',
  'support.ticket_detail.today': 'Today',
  'support.ticket_detail.yesterday': 'Yesterday',

  // Ticket Info Screen
  'support.ticket_info.title': 'Ticket Details',
  'support.ticket_info.conversation': 'Conversation',
  'support.ticket_info.messages': 'messages',
  'support.ticket_info.subject': 'Subject',
  'support.ticket_info.topic': 'Topic',
  'support.ticket_info.priority': 'Priority',
  'support.ticket_info.priority.low': 'Low',
  'support.ticket_info.priority.medium': 'Medium',
  'support.ticket_info.priority.high': 'High',
  'support.ticket_info.priority.urgent': 'Urgent',
  'support.ticket_info.created': 'Created',
  'support.ticket_info.updated': 'Last Updated',
  'support.ticket_info.resolved': 'Resolved',
  'support.ticket_info.closed': 'Closed',
  'support.ticket_info.original_message': 'Original Message',
  'support.ticket_info.not_found': 'Ticket not found',
  'support.ticket_info.closed_banner': 'This ticket has been closed.',

  // ==================== PROFILE EXTRAS ====================
  'profile.account_type_label': 'Account type',
  'profile.invite.link_shared': 'Link shared!',
  'profile.invite.title': 'Invite your friends',
  'profile.invite.hero_title': 'Share VYZI and both earn rewards',
  'profile.invite.hero_desc': 'Invite your friends to use VYZI. When an application is successfully completed, you each receive a €10 Amazon voucher.',
  'profile.invite.link_label': 'Personal invite link',
  'profile.invite.copy': 'Copy',
  'profile.invite.share_link': 'Share your link',
  'profile.invite.you_earn': 'You receive',
  'profile.invite.you_earn_when': 'An Amazon voucher after your friend’s utility is activated.',
  'profile.invite.friend_gets': 'Your friend receives',
  'profile.invite.friend_gets_when': 'An Amazon voucher after their utility is activated.',
  'profile.invite.stats_title': 'Your invitations',
  'profile.invite.invites_sent': 'Invites sent',
  'profile.invite.invites_sent_desc': 'Links shared',
  'profile.invite.completed': 'Activated invitations',
  'profile.invite.completed_desc': 'Successfully completed applications',
  'profile.invite.earnings_title': 'Total earnings',
  'profile.invite.earnings_status': 'AVAILABLE',
  'profile.invite.earnings_type': 'Total in Amazon vouchers',
  'profile.invite.tip': 'Tip',
  'profile.invite.tip_text': 'Share your link with friends and family to earn more.',
  'profile.invite.share_text': 'Use my referral link to save on your utility bills',

  // ==================== EMAIL BILL RECEIVED ====================
  'home.email_bill_received.title': 'Request Created!',
  'home.email_bill_received.subtitle': 'Your request has been created successfully.\nOur team will process your bill once received via email.',
  'home.email_bill_received.analysis_in_progress': 'Processing Your Request',
  'home.email_bill_received.analysis_time_info': 'The review is generally completed within 24 working hours. We will update you as soon as it is finished.',

  // ==================== COMPLETE REQUEST FORM EXTRAS ====================
  'request.offer_details.price_formula': 'Energy Price: PUN GME + \u20AC 0.01/KWh',
  'request.form.residential_matches_delivery': 'Does your residential address match your supply address?',
  'request.form.registered_office_matches_delivery':
      'Is the registered office the same as the supply address?',
  'request.form.address_yes_same': 'Yes, it\'s the same',
  'request.form.address_no_different': 'No, it\'s different',
  'request.form.no_selection_info': 'Enter your residential address below.',
  'request.form.no_selection_info_business':
      'Enter the company’s registered office below.',
  'request.form.id_document_instruction': 'Upload a valid identity document to complete your request. You can use an identity card, driving licence or passport. Include the front and back where applicable, in one file or as separate photos or files.',
  'request.form.upload_file_button': 'Upload document',
  'request.form.upload_formats': 'PDF or photo from gallery/files',
  'request.form.take_photo_button': 'Take photo',
  'request.form.take_photo_hint': 'Front and back',
  'request.form.id_camera_title': 'Photograph your document',
  'request.form.files_selected': 'file(s) selected',
  'request.form.scan_document_button': 'Scan Document',
  'request.form.scan_with_camera': 'Scan with camera',
  'request.form.payment_method_title': 'Payment method',
  'request.form.full_name_label': 'Full name',
  'request.form.tax_code_label': 'Tax code',
  'request.form.first_name': 'First Name',
  'request.form.last_name': 'Last Name',
  'request.form.tax_code_error': 'Enter a valid Codice Fiscale (16 characters).',
  'request.form.tax_code_vat_not_accepted': 'A VAT number cannot be used here. Enter the Codice Fiscale of the account holder (16 characters).',
  'request.form.tax_code_error_check': 'The last character does not match the rest of the code — it should be @char.',
  'request.form.tax_code_required_hint': 'A valid Codice Fiscale is required for direct debit.',
  'request.form.vat_label': 'VAT Number',
  'request.form.vat_error': 'Enter a valid VAT number — 11 digits, and the last one must match the rest.',
  'request.form.vat_tax_code_not_accepted': 'A Codice Fiscale cannot be used here. A company is identified by its VAT number (11 digits).',
  'request.form.vat_required_hint': 'A valid VAT number is required for direct debit.',
  'request.form.holder_tax_id_label': 'Holder Tax Code / VAT',
  'request.form.holder_tax_id_error': 'Enter a valid Codice Fiscale (16 characters) or VAT number (11 digits).',
  'request.form.holder_tax_id_missing': 'Not on your profile',
  'request.form.holder_tax_id_invalid': 'Not valid',
  'request.form.holder_tax_id_add': 'Add it in your personal details',
  'request.form.holder_tax_id_fix': 'Fix it in your personal details',
  'request.form.holder_first_name_required': 'Holder first name is required.',
  'request.form.holder_last_name_required': 'Holder last name is required.',
  'request.form.contract_send_info': 'Once your request is complete, we will send you the contract within 24 working hours for signature.',
  'request.payment.sdd_subtitle_full': 'Automatic payment from your bank account.',
  'request.payment.postal_bill_subtitle_full': 'You will receive a payment slip to pay your bill.',
  'request.invoice.destination_preview': 'Your bill will be sent to:',
  'request.form.conform_address': 'Confirm Address',
  'request.form.complete_request_title': 'Complete your request',
  'request.form.personal_info_title': 'Personal Information',
  'request.form.edit': 'Edit',
  'request.form.save_holder_details': 'Save holder details',
  'request.form.edit_holder_details': 'Edit holder details',
  'request.form.holder_details_saved': 'Details saved',
  'request.form.first_name_field': 'First Name',
  'request.form.last_name_field': 'Last Name',
  'request.form.email_field': 'Email',
  'request.form.phone_field': 'Phone',
  'request.form.pod_number_field': 'POD Number',
  // A business account's summary: the company and its owner are two separate
  // parties to the contract, each with its own identifier.
  'request.form.company_name_field': 'Company Name',
  'request.form.owner_first_name_field': 'Owner First Name',
  'request.form.owner_last_name_field': 'Owner Last Name',
  'request.form.owner_tax_code_field': 'Owner Tax Code',
  'request.form.pec_field': 'PEC (certified email)',
  'request.form.company_name_required': 'Company name is required',
  'request.form.vat_required': 'VAT number is required',
  'request.form.owner_first_name_required': 'Owner first name is required',
  'request.form.owner_last_name_required': 'Owner last name is required',
  'request.form.pec_invalid': 'Enter a valid PEC address',
  'request.form.payment_method_info': 'Payment Method: ',
  'request.form.compatibility_info': 'Compatibility: Residential',
  'request.form.identity_verification_title': 'Identity verification',
  'request.form.required': 'Required',
  'request.form.identity_required_hint': 'Please upload at least one file to activate the offer.',
  'request.form.invoice_delivery_title': 'Bill delivery method',
  'request.form.invoice_delivery_tip': 'Our advice: choose a digital bill to receive it faster and avoid postal delays.',
  'request.form.iban_same_as_contract': 'Yes, the bank account holder is the same as the contract holder.',
  'request.form.iban_label': 'IBAN',
  'request.form.iban_hint': 'Enter your IBAN',
  'request.form.iban_error': 'Please enter a valid 27-character Italian IBAN.',
  'request.form.iban_required_hint': 'Please enter a valid IBAN to activate the offer.',
  'request.form.prefilled_email': 'Pre-filled email from your profile',
  'request.form.email_for_invoice': 'Email for invoice',
  'request.form.pec_for_invoice': 'PEC for invoice',
  'request.form.yes': 'Yes',
  'request.form.no': 'No',
  'request.form.enter_shipping_address': 'Enter your shipping address',
  'request.form.email_invoice_hint': 'Enter email for invoice',
  'request.form.pec_invoice_hint': 'Enter PEC for invoice',
  // Address hints and validation messages
  'request.form.street_hint': 'Enter street',
  'request.form.street_number_hint': 'e.g. 10',
  'request.form.city_hint': 'Enter city',
  'request.form.postal_code_hint': 'e.g. 20100',
  'request.form.province_hint': 'Enter province',
  'request.form.street_required': 'Please enter the street',
  'request.form.street_number_required': 'Please enter the street number',
  'request.form.city_required': 'Please enter city',
  'request.form.postal_code_required': 'Please enter the postal code',
  'request.form.postal_code_invalid': 'The postal code must be 5 digits',
  'request.form.province_required': 'Please enter the province',
  'request.form.address_missing': 'Address not available',
  'request.form.complete_supply_address':
      'Complete the supply address to activate the offer.',
  'request.form.address_required_hint':
      'Please complete all required addresses to activate the offer.',
  'request.form.shipping_match_required':
      'Please select where paper invoices should be sent',
  'request.form.first_name_required': 'First name is required',
  'request.form.last_name_required': 'Last name is required',
  'request.form.pod_number_required': 'POD number is required',
  'request.form.phone_required': 'Phone number is required',
  'request.form.address_match_required': 'Please select whether the residential address matches the delivery address',
  'request.form.address_match_required_business':
      'Please select whether the registered office matches the delivery address',
  'request.form.profile_update_failed':
      'Could not save your personal information. Please try again.',
  'request.form.invoice_email_error': 'Enter a valid email address',
  'request.form.invoice_email_required_hint':
      'Please enter a valid email address for your digital invoices.',

  // ==================== PERSONAL DATA ====================
  'personal_data.title': 'Personal Data',
  'personal_data.subtitle': 'Update your account information and how\nwe contact you.',
  'personal_data.change_photo': 'Change photo',
  'personal_data.camera': 'Camera',
  'personal_data.gallery': 'Gallery',
  'personal_data.first_name': 'First Name',
  'personal_data.last_name': 'Last Name',
  'personal_data.email': 'Email',
  'personal_data.phone': 'Phone Number',
  'personal_data.tax_code': 'Tax Code',
  'personal_data.pec_invalid': 'Enter a valid PEC address',
  'personal_data.privacy_title': 'Privacy First',
  'personal_data.privacy_desc': 'Your data is encrypted and managed according to our premium protection standards. We never share your personal data with third parties without your consent.',
  'personal_data.first_name_hint': 'Enter your first name',
  'personal_data.last_name_hint': 'Enter your last name',
  'personal_data.email_hint': 'Enter your email',
  'personal_data.phone_hint': 'Enter your phone number',
  'personal_data.business_section': 'Business data',
  'personal_data.business_section_desc':
      'The details of the company this business account acts for.',
  'personal_data.job_role': 'Job role',
  'personal_data.job_role_hint': 'Select your role',
  'personal_data.company_name': 'Company Name',
  'personal_data.company_name_hint': 'Enter your company name',
  'personal_data.vat': 'VAT Number',
  'personal_data.vat_hint': '11 digits, no spaces',
  'personal_data.vat_invalid': 'Enter a valid VAT number — 11 digits, and the last one must match the rest.',
  'personal_data.tax_code_invalid': 'Enter a valid Codice Fiscale — 16 characters, and the last one must match the rest.',
  'personal_data.vat_taken': 'This VAT number is already registered to another account',
  'personal_data.tax_code_hint': 'Enter your tax code',
  // On a business account the tax code is the owner's, while the VAT number
  // identifies the company: two different parties, two identifiers.
  'personal_data.owner_tax_code': 'Owner Tax Code',
  'personal_data.owner_tax_code_hint': "Enter the owner's tax code",
  'personal_data.pec': 'PEC (certified email)',
  'personal_data.pec_hint': 'e.g. company@pec.it',
  'personal_data.save_changes': 'Save Changes',
  'personal_data.cancel_discard': 'Cancel and discard',
  'personal_data.update_success_title': 'Profile Updated',
  'personal_data.update_success_message': 'Your profile has been updated successfully.',
  'personal_data.update_error_title': 'Update Failed',
  'personal_data.update_error_message': 'An error occurred while updating your profile. Please try again.',

  // ==================== SELECT UTILITY ====================
  'select_utility.title': 'Select Utility',
  'select_utility.heading': 'Which utilities do you want\nto optimize?',
  'select_utility.subtitle': 'Select the service for which you want to find the best offers',
  'select_utility.luce_sublabel': 'Optimize your electricity bill',
  'select_utility.gas_sublabel': 'Reduce your gas expenses',
  'select_utility.tip_label': 'Tip: ',
  'select_utility.tip_text': 'You can upload more bills later to compare all your utilities.',

  // ==================== UPLOAD BILL ====================
  'upload_bill.appbar_title': 'Upload your bill',
  'upload_bill.heading_electricity': 'Upload your electricity bill',
  'upload_bill.heading_gas': 'Upload your gas bill',
  'upload_bill.subtitle': 'Choose the most convenient method for you',
  'upload_bill.info_text': 'We need your bill to analyse your current offer and check for better-value alternatives.',
  'upload_bill.info_link': 'Why do we need it?',
  'upload_bill.info_popup_title': 'Why do we need your bill?',
  'upload_bill.info_popup_body': 'Your bill contains essential details about your current energy plan, such as your consumption, pricing, and contract terms.\n\nBy analyzing this information, we can accurately compare your current plan with available offers on the market and suggest alternatives that could save you money.\n\nWithout your bill, we wouldn\'t be able to provide personalized recommendations tailored to your actual usage.',
  'upload_bill.info_popup_close': 'Got it',
  'upload_bill.upload_file': 'Upload a file',
  'upload_bill.upload_formats': 'PDF or photo',
  'upload_bill.scan_file': 'Take a photo',
  'upload_bill.scan_use_camera': 'Photograph your bill',
  'upload_bill.or_divider': 'OR',
  'upload_bill.send_email': 'Send by email',
  'upload_bill.send_email_address': 'Forward to @email',
  'upload_bill.looking_for_title': 'What we analyse from your bill',
  'upload_bill.looking_for_1': 'Current supplier and offer',
  'upload_bill.looking_for_2': 'Annual consumption',
  'upload_bill.looking_for_3': 'Energy price and fixed costs',
  'upload_bill.looking_for_4': 'Supply address',
  'upload_bill.scanner_title': 'Scan your bill',
  'upload_bill.scanner_hint': 'Align your bill in the frame',
  'upload_bill.uploading': 'Uploading...',
  'upload_bill.upload_success': 'Bill uploaded successfully!',
  'upload_bill.upload_failed': 'Upload failed. Please try again.',
  'upload_bill.file_too_large': 'File too large. Maximum 10 MB.',
  'upload_bill.invalid_file_type': 'Invalid file type. Use PDF, JPG, or PNG.',
  'upload_bill.select_source': 'Select source',
  'upload_bill.photo_gallery': 'Photo from gallery',
  'upload_bill.pdf_document': 'PDF document',
  'upload_bill.take_photo': 'Take photo',
  'upload_bill.upload_button': 'Upload your bill',
  'upload_bill.remove_file': 'Remove',
  'upload_bill.extracting': 'Analyzing bill...',
  'upload_bill.extraction_complete': 'Data extracted from bill',
  'upload_bill.extraction_verify': 'Verify the extracted data before uploading.',
  'upload_bill.extraction_failed': 'Could not read the bill. Try again with a clearer photo.',
  'upload_bill.extraction_no_data': 'No data found in the bill. Try again with a clearer photo.',
  'upload_bill.extraction_missing_fields': 'Some required data could not be found',
  'upload_bill.extraction_retry_hint': 'Try again with a clearer photo or a readable PDF.',
  'upload_bill.field_supplier': 'Supplier',
  'upload_bill.field_pod': 'POD',
  'upload_bill.field_pdr': 'PDR',
  'upload_bill.field_total': 'Total amount',
  'upload_bill.field_consumption': 'Consumption',
  'upload_bill.field_cost_per_unit': 'Cost per unit',
  'upload_bill.field_fixed_charges': 'Fixed charges',
  'upload_bill.field_taxes': 'Taxes',
  'upload_bill.field_period': 'Period',
  'upload_bill.field_address': 'Supply address',
  'upload_bill.field_tax_code': 'Tax code',
  'upload_bill.field_vat': 'VAT number',
  'upload_bill.field_contract': 'Contract No.',
  'upload_bill.field_meter': 'Meter number',
  'upload_bill.field_customer': 'Account holder',

  // Multi-file upload
  'upload_bill.files_selected': '@count files selected',
  'upload_bill.clear_all': 'Clear all',
  'upload_bill.add_more_files': 'Add More Files',
  'upload_bill.no_files_selected': 'No files selected',
  'upload_bill.tap_to_select': 'Tap Upload File to get started',
  'upload_bill.upload_x_files': 'Upload @count Files',
  'upload_bill.uploading_progress': 'Uploading @current of @total files',
  'upload_bill.cancel': 'Cancel',
  'upload_bill.batch_complete': 'Complete: @uploaded uploaded, @failed failed',
  'upload_bill.retry_failed': 'Retry Failed',
  'upload_bill.done': 'Done',
  'upload_bill.max_files_reached': 'Maximum 10 files already selected.',
  'upload_bill.file_card': 'File',
  'upload_bill.retry_file': 'Retry upload',
  'upload_bill.status_pending': 'Pending',
  'upload_bill.status_extracting': 'Analyzing...',
  'upload_bill.status_extracted': 'Ready',
  'upload_bill.status_uploading': 'Uploading',
  'upload_bill.status_uploaded': 'Uploaded',
  'upload_bill.status_failed': 'Failed',
  'upload_bill.file_validation_title': 'File Selection',
  'upload_bill.skipped_duplicates': 'Skipped duplicates: @files',
  'upload_bill.skipped_invalid': 'Unsupported files: @files',
  'upload_bill.skipped_oversized': 'Too large: @files (max 10 MB)',
  'upload_bill.skipped_over_limit': '@count files skipped: maximum 10 files',
  'upload_bill.error_network': 'Network error. Check your connection.',
  'upload_bill.error_timeout': 'Request timed out. Please try again.',
  'upload_bill.error_server': 'Server error. Please try again later.',
  'upload_bill.error_file_access': 'Could not access file. It may no longer be available.',
  'upload_bill.error_storage_access': 'Storage access error. Please try again.',
  'upload_bill.permission_required_title': 'Permission Required',
  'upload_bill.permission_required_message': 'Storage permission is required to select files.',
  'upload_bill.open_settings': 'Settings',
  'upload_bill.take_another_photo': 'Take Another Photo',
  'upload_bill.camera_title': 'Scan your bills',
  'upload_bill.camera_done': 'Done',
  'upload_bill.camera_initializing': 'Starting camera...',
  'upload_bill.camera_error': 'Could not start camera. Please check permissions.',
  'upload_bill.camera_limit_reached': 'Maximum photos reached',
  'upload_bill.camera_discard_title': 'Discard photos?',
  'upload_bill.camera_discard_message': 'You have @count photos. Discard them?',
  'upload_bill.camera_discard_yes': 'Discard',
  'upload_bill.camera_discard_no': 'Keep shooting',

  'sign_contract.appbar_title': 'Sign Your Contract',
  'sign_contract.action_required': 'Action Required',
  'sign_contract.ready_title': 'Ready to Sign',
  'sign_contract.ready_desc': 'Your contract is ready! Sign it to complete your switch to @supplier.',
  'sign_contract.ready_desc_generic': 'Your contract is ready! Sign it to complete your switch.',
  'sign_contract.pill_active': 'Active',
  'sign_contract.active_title': 'Contract Active',
  'sign_contract.active_desc': 'Your new supply is active. You can find it under My Utilities.',
  'sign_contract.pill_in_activation': 'In Activation',
  'sign_contract.in_activation_title': 'Utility In Activation',
  'sign_contract.in_activation_desc': 'The switch to your new supplier is under way. You can already find it under My Utilities and we will let you know as soon as it goes live.',
  'sign_contract.closed_title': 'Contract Closed',
  'sign_contract.closed_desc': 'This contract is no longer active. Get in touch with support if you need help.',
  'sign_contract.pill_preparing': 'In Preparation',
  'sign_contract.preparing_title': 'Contract Being Prepared',
  'sign_contract.preparing_desc': 'We are preparing your contract. You will be notified as soon as it is ready to sign.',
  'sign_contract.supplier_label': 'Supplier',
  'sign_contract.offer_name_label': 'Offer Name',
  'sign_contract.activation_date_label': 'Activation Date',
  'sign_contract.savings_label': 'Estimated Annual Savings',
  'sign_contract.savings_suffix': '/year',
  'sign_contract.error_load': 'Unable to load your contract.',
  'sign_contract.error_missing_bill': 'Contract not found.',
  'sign_contract.view_tutorial': 'View Signing Tutorial',

  // ==================== BUSINESS JOB ROLES ====================
  'business_role.ceo': 'CEO / Founder',
  'business_role.manager': 'Manager',
  'business_role.finance': 'Financial Manager',
  'business_role.it': 'IT Administrator',
  'business_role.other': 'Other',

  // ==================== TERMS & CONDITIONS ====================
  'terms.title': 'Terms and Conditions',

  // ==================== AGREEMENTS ====================
  'agreements.how_to_1': 'Copy your discount code using the button above',
  'agreements.how_to_2': 'Visit the partner\'s website: ',
  'agreements.how_to_3': 'Show the code in store, or enter it at checkout when ordering online',
  'agreements.how_to_4': 'Enjoy your exclusive discount!',

  // ==================== OFFER DETAILS EXTRA STRINGS ====================
  'offer.details_title': 'Offer Details',
  'offer.price_type_link': 'What does this mean?',
  // Indexed / variable offers: the price follows a market index — PUN GME for
  // electricity, PSV for gas — which is why the index is a parameter.
  'offer.price_type_indexed_title': 'Indexed price: how does it work?',
  'offer.price_type_indexed_text': 'The energy price varies following the wholesale market trend, represented by the @index.',
  'offer.price_type_indexed_note': 'The cost can increase or decrease over time based on market changes.',
  // Fixed-price offers: no mention of PUN, indexation or spread.
  'offer.price_type_fixed_title': 'Fixed price: what does it mean?',
  'offer.price_type_fixed_text': 'The energy price stays the same for the whole contract period stated in the offer, regardless of wholesale market fluctuations.',
  'offer.price_type_fixed_note': 'You know from the start what you will pay: the cost does not change if the market rises.',
  'offer.energy_price_link': 'How is it calculated?',
  'offer.price_calc_title': 'Price Calculation',
  'offer.price_calc_subtitle': 'The price is calculated as:',
  'offer.price_calc_footer': 'This transparent formula tracks the\nofficial energy market index.',
  'offer.max_benefit': 'ESTIMATED ANNUAL SAVINGS',
  'offer.estimated_savings': 'ESTIMATED SAVINGS',
  'offer.economic_conditions': 'Economic conditions',
  'offer.economic_conditions_unavailable': 'Document not yet available',

  // Document Viewer
  'document_viewer.loading': 'Loading document...',
  'document_viewer.error': 'Unable to load document',
  'document_viewer.save_error_title': 'Error',
  'document_viewer.save_error_message': 'Could not save document',
  'document_viewer.unsupported':
      'This file type cannot be previewed in the app.',
  'document_viewer.open_external': 'Open outside the app',
  'document_viewer.open_external_error':
      'No app on this device can open this file.',

  'offer.select_offer': 'Select this Offer',

  // ==================== AUTH VALIDATION ====================
  'auth.validation.error': 'Error',
  'auth.validation.warning': 'Warning',
  'auth.validation.success': 'Success',
  'auth.validation.info': 'Info',
  'auth.reset_password.empty_error': 'Please enter passwords',
  'auth.reset_password.min_length_error': 'Password must be at least 8 characters',
  'auth.reset_password.lowercase_error': 'Password must contain at least one lowercase letter',
  'auth.reset_password.uppercase_error': 'Password must contain at least one uppercase letter',
  'auth.reset_password.number_error': 'Password must contain at least one number',
  'auth.reset_password.special_char_error': 'Password must contain at least one special character',
  'auth.reset_password.success_message': 'Password reset successfully',
  'auth.reset_password.failed_error': 'Failed to reset password',
  'auth.otp.verified_success': 'Code verified',
  'auth.otp.verification_failed': 'Code verification failed',
  'auth.otp.resend_title': 'Code requested',
  'auth.otp.resend_message': 'If the email address is registered and requires verification, we have sent a new code.',
  'auth.forgot_password.otp_sent_success': 'If the email address is registered, we have sent a code to reset your password.',
  'auth.forgot_password.send_failed_error': 'We could not send the code right now. Please try again in a moment.',
  'auth.signup.registration_failed_default': 'Registration failed. Please try again.',
  'auth.signup.password_requirements_unmet': 'Password does not meet security requirements',
  'auth.session_expired.title': 'Session Expired',
  'auth.session_expired.message': 'Your session has expired. Please sign in again.',

  // ==================== FAQ ====================
  'faq.title': 'Frequently Asked Questions',
  'faq.error': 'Something went wrong loading FAQs. Please try again.',
  'faq.retry': 'Retry',
  'faq.empty': 'No FAQs available at the moment.',

  // ==================== REQUEST DETAILS ====================
  'request.details.title': 'Request Details',
  'request.details.processing_title': 'Processing your Request',
  'request.details.processing_desc': 'We are working on your switch. No action\nrequired from you at this time.',
  'request.details.submission_date': 'Submission date',
  'request.details.in_analysis': 'Under analysis',
  'request.details.info_message': 'The review is generally completed within 24 working hours. We will update you as soon as it is finished.',

  // ==================== BILLS FILTERS ====================
  'bills.filter.bill_type': 'Bill Type:',
  'bills.filter.all_types': 'All',
  'bills.filter.electricity': 'Electricity',
  'bills.filter.gas': 'Gas',
  'bills.filter.status': 'Status:',
  'bills.filter.all_statuses': 'All',
  'bills.filter.uploaded': 'Uploaded',
  'bills.filter.analyzing': 'Analyzing',
  'bills.filter.analyzed': 'Analyzed',
  'bills.filter.error': 'Error',
  'bills.list.your_bills': 'Your Bills',
  'bills.list.found': 'found',
  'bills.list.page_of': 'Page @current of @total',

  // ==================== BILL DETAIL LABELS ====================
  'bills.detail.bill_type': 'Bill Type',
  'bills.detail.status': 'Status',
  'bills.detail.pod_number': 'POD Number',
  'bills.detail.pdr_number': 'PDR Number',
  'bills.detail.billing_period': 'Billing Period',
  'bills.detail.total_amount': 'Total Amount',
  'bills.detail.consumption': 'Consumption',
  'bills.detail.cost_per_unit': 'Cost per Unit',
  'bills.detail.fixed_charges': 'Fixed Charges',
  'bills.detail.taxes': 'Taxes',
  'bills.detail.supply_address': 'Supply Address',
  'bills.detail.codice_fiscale': 'Tax Code',
  'bills.detail.partita_iva': 'VAT Number',
  'bills.detail.contract_number': 'Contract No.',
  'bills.detail.meter_number': 'Meter Number',
  'bills.detail.customer_name': 'Account Holder',
  'bills.detail.status_pending_email': 'Our team is checking your bill, the process will take 7 business days',
  'bills.detail.status_uploaded': 'Bill uploaded, awaiting analysis',
  'bills.detail.status_analyzing': 'Analysis in progress...',
  'bills.detail.status_analyzed': 'Analysis completed',
  'bills.detail.status_error': 'Error during analysis',
  'bills.detail.status_verification_required': 'Verification required — please send the requested documents',
  'bills.detail.status_verification_review': 'Our team is reviewing your bill data',
  'bills.detail.status_verified': 'Your bill data has been verified',
  'bills.detail.status_offer_accepted': 'You accepted an offer. Your contract is being prepared.',
  'bills.detail.status_awaiting_activation': 'Your utility is being activated',
  'bills.detail.potential_savings': 'POTENTIAL SAVINGS',
  'bills.detail.estimated_annual': 'Estimated Annual Savings',

  // ==================== BILL MODEL DISPLAY ====================
  'bills.type.electricity': 'Electricity',
  'bills.type.gas': 'Gas',
  'bills.status.pending_email': 'Pending (Email)',
  'bills.status.uploaded': 'Uploaded',
  'bills.status.analyzing': 'Analyzing',
  'bills.status.analyzed': 'Analyzed',
  'bills.status.error': 'Error',
  'bills.status.verification_required': 'Verification Required',
  'bills.status.verification_review': 'Under analysis',
  'bills.status.verified': 'Verified',
  'bills.status.offer_sent': 'Offers Sent',
  'bills.status.offer_accepted': 'Offer Accepted',
  'bills.status.case_created': 'Case Created',
  'bills.status.contract_sent': 'Contract Sent',
  'bills.status.awaiting_activation': 'In Activation',
  'bills.status.activated': 'Activated',
  'bills.status.cancelled': 'Cancelled',
  'bills.supplier.unknown': 'Unknown supplier',
  'bills.period.from': 'From',

  // ==================== ONBOARDING ====================
  'onboarding.question': 'How do you want to use VYZI?',
  'onboarding.subtitle': 'Choose your account type',
  'onboarding.private': 'Private',
  'onboarding.private_desc': 'For personal use and household utilities',
  'onboarding.business': 'Business',
  'onboarding.business_desc': 'For businesses and professionals with a VAT number',
  'onboarding.private_point1': 'Manage your home electricity and gas utilities',
  'onboarding.private_point2': 'Compare available offers',
  'onboarding.private_point3': 'Track consumption and savings',
  'onboarding.business_point1': 'Manage multiple business utilities',
  'onboarding.business_point2': 'Compare electricity and gas offers for your business',
  'onboarding.business_point3': 'Manage your VAT number and company details',
  'onboarding.sign_in': 'Sign in',
  'onboarding.create_account': 'Create an account',

  // ==================== REQUEST OFFERS ====================
  'request.filter.payment_method': 'Payment Method:',
  'request.filter.all': 'All',
  'request.filter.direct_debit': 'Direct Debit',
  'request.filter.postal_slip': 'Postal Order',
  'request.offers.payment_method_label': 'Payment Method',
  'request.offers.none_for_payment_method':
      'No offers accept this payment method.\nTry a different filter.',
  'request.offers.best_for_you': 'Best Offers for You',
  'request.offers.found': 'found',
  'request.offers.energy_price_fixed': 'Energy Price (Fixed): @price',
  'request.offers.energy_price_indexed': 'Energy Price: @index + @spread',
  'request.offers.energy_price_spread': 'Spread',
  'request.offers.estimated_savings': 'Est. annual savings',
  'request.offers.empty_title': 'Your offers, under control',
  'request.offers.empty_desc': 'We analyse your bill and check for better-value offers for you.',
  'request.offers.view_details': 'View Details',
  'request.offers.amount_label': 'Amount',
  // Shown when a "new offers" notification narrowed the list to one request.
  'request.offers.for_request': 'Offers for @supply',
  'request.offers.for_this_request': 'Offers for this request',
  'request.offers.show_all': 'Show all',
  'request.offers.none_for_request':
      'There are no offers on this request yet.\nWe will let you know as soon as there are.',

  // ==================== AGREEMENTS ====================
  'agreements.title': 'Agreements',
  'agreements.subtitle': 'Exclusive discounts for you',
  'agreements.your_benefits': 'Your Benefits',
  'agreements.benefits_desc': 'Enjoy exclusive discounts at our partner restaurants as a valued member.',
  'agreements.details_title': 'Agreement Details',
  'agreements.offer_date': 'Offer Date: ',
  'agreements.exclusive_discount': 'Your Exclusive Discount',
  'agreements.discount_code': 'Discount Code',
  'agreements.copied': 'Copied!',
  'agreements.copy': 'Copy',
  'agreements.location': 'Location',
  'agreements.open_maps': 'Open in Google Maps',
  'agreements.how_to_use': 'How to Use Your Discount',
  'agreements.no_agreements': 'No agreements available at the moment',
  'agreements.error_loading': 'Failed to load agreements',
  'agreements.retry': 'Retry',

  // ==================== STATIC PAGES ====================
  'static_page.loading': 'Loading...',
  'static_page.error': 'Unable to load content. Please try again later.',
  'static_page.not_available': 'This content is not available yet. Please check back later.',
  'static_page.retry': 'Retry',

  // ==================== LEGAL DOCUMENTS & CONSENT ====================
  'legal.version': 'Version',
  'legal.updated_on': 'Updated',
  'legal.accepted_on': 'You accepted version @version on @date.',
  'legal.pending_update': 'You accepted version @accepted. Version @current is now in force and needs your approval.',
  'legal.not_yet_accepted': 'You have not accepted this document yet.',
  'legal.gate_title': 'Please review and accept',
  'legal.step': 'Step @current of @total',
  'legal.whats_changed': "WHAT'S CHANGED",
  'legal.replaces_version': 'replaces version @version',
  'legal.scroll_to_end': 'Scroll to the end to continue',
  'legal.accept_checkbox': 'I have read and accept @title (version @version).',
  'legal.accept_and_continue': 'Accept and continue',
  'legal.accept_and_next': 'Accept and continue',
  'legal.logout': 'Log out',
  'legal.decline_title': 'Continue without accepting?',
  'legal.decline_body': 'You need to accept the updated documents to keep using EasyRisparmio. You will be signed out and can accept the next time you sign in.',
  'legal.decline_cancel': 'Go back',
  'legal.decline_confirm': 'Sign out',
  'legal.accept_failed': 'We could not record your acceptance. Please try again.',
  'legal.version_changed': 'A newer version was just published. Loading it now...',

  // ==================== CASE / PRATICA ====================
  'case.status.new': 'New request',
  'case.status.in_progress': 'In progress',
  'case.status.documents_pending': 'Documents required',
  'case.status.contract_sent': 'Contract sent',
  'case.status.awaiting_activation': 'Utility in activation',
  'case.status.activated': 'Utility activated',
  'case.status.rejected': 'Request rejected',
  'case.status.cancelled': 'Request cancelled',

  'case.step.sent': 'Sent',
  'case.step.in_progress': 'In Progress',
  'case.step.contract': 'Contract',
  'case.step.signed': 'Signed',
  'case.step.active': 'Active',
  'case.step.contract_sent': 'Contract Sent',
  'case.step.activated': 'Activated',

  'case.detail.title': 'Case Details',
  'case.detail.pratica': 'Case',
  'case.detail.details_button': 'Case Details',
  'case.detail.error.not_found': 'Case ID not found',
  'case.detail.error.load_failed': 'Unable to load data',
  'case.detail.error.connection': 'Connection error',
  'case.detail.selected_offer': 'Selected offer',
  'case.detail.contract': 'Contract',
  'case.detail.contract_preparing': 'Contract being prepared',
  'case.detail.contract_preparing_desc': 'The contract will be sent to you soon.',
  'case.detail.sent_via': 'Sent',
  'case.detail.download_contract': 'Download Contract',
  'case.detail.upload_signed': 'Upload Signed Contract',
  'case.detail.waiting_confirmation': 'Waiting for operator confirmation',
  'case.detail.utility_in_activation': 'Utility in activation',
  'case.detail.utility_activated': 'Utility activated!',
  'case.detail.activated_on': 'Activated on',
  'case.detail.upload_success': 'Signed contract uploaded successfully',
  'case.detail.upload_error': 'Unable to upload signed contract',
  'case.detail.contract_documents': 'Contract Documents',
  'case.detail.signed_documents': 'Signed Documents',
  'case.detail.sign_guideline': 'Contract Signing Guide',

  // ==================== BILL STATUS MESSAGES ====================
  'bills.status_msg.offer_sent': 'Offers available',
  'bills.status_msg.case_created': 'Case in progress',
  'bills.status_msg.contract_sent': 'Contract sent',
  'bills.status_msg.activated': 'Utility activated',
  'bills.status_msg.cancelled': 'Case cancelled',

  // ==================== NOTIFICATIONS ====================
  'notifications.title': 'Notifications',
  'notifications.empty': 'No notifications',
  'notifications.mark_all_read': 'Mark all as read',
  'notifications.all_read': 'All notifications marked as read',
  'notifications.load_more': 'Load more',
  'notifications.type.bill_analyzed': 'Bill Analyzed',
  'notifications.type.bill_verification': 'Verification Required',
  'notifications.type.offer_available': 'New Offer',
  'notifications.type.case_update': 'Case Update',
  'notifications.type.contract_status': 'Contract Update',
  'notifications.type.referral_status': 'Referral Update',
  'notifications.type.contract_verification': 'Contract Verification',
  'notifications.type.activation_complete': 'Activation Complete',
  'notifications.type.support_reply': 'Support Reply',
  'notifications.type.general': 'General',

  // ==================== BILL VERIFICATION ====================
  'verification.title': 'Verification',
  'verification.admin_message_title': 'Message from Admin',
  'verification.upload_documents': 'Send Documents',
  'verification.upload_hint':
      'Upload a file or take a photo of the requested document.',
  'verification.your_message': 'Your Message (optional)',
  'verification.your_message_hint': 'Add any additional information...',
  'verification.submit': 'Submit Document',
  'verification.file_required': 'Please add at least one document',
  'verification.missing_documents_title': 'No Documents',
  'verification.upload_retry':
      'We could not upload your documents. Please try again.',
  'verification.submitted_title': 'Documents Sent',
  'verification.submitted_message':
      'Your documents have been sent. We will review them and get back to you.',
  'verification.error_title': 'Error',
  'verification.submit_failed': 'Failed to send. Please try again.',
  'verification.load_failed': 'Failed to load verification details',
  'verification.retry': 'Retry',
  'verification.done': 'Done',
  'verification.none_pending': 'No pending verification',
  'verification.history_title': 'Verification History',
  'verification.round': 'Round @number',
  'verification.status_pending': 'AWAITING RESPONSE',
  'verification.status_submitted': 'SUBMITTED',
  'verification.status_resolved': 'RESOLVED',
  'verification.type_bill': 'BILL DOCUMENT',
  'verification.type_contract': 'SIGNED CONTRACT',
  'verification.admin_request': 'Admin Request',
  'verification.your_response': 'Your Response',
  'verification.uploaded_files': 'Uploaded Files (@count)',
  'verification.no_details': 'No documents submitted.',
  'verification.image_load_failed': 'Failed to load image',
  'home.email_bill.hero_title': 'Send by email',
  'home.email_bill.hero_subtitle': 'Forward your bill to the address below.',
  'my_utility.empty_desc': 'Upload a bill to compare offers and request activation of a new utility.',
  'bills.detail.via_email': 'By email',
  'offer.savings_comparison': 'Compared with your current offer',
  'common.copied': 'Copied',
  'home.email_bill.copied': 'Email address copied to clipboard',
  'home.email_bill.failed': 'We could not create your request. Please try again.',
  'system.password_reused': 'Your new password must be different from your current password.',
  'system.current_password_incorrect': 'Your current password is incorrect.',
  'system.email_registered': 'This email address is already registered.',
  'system.code_expired': 'The code is invalid or has expired. Request a new code.',
  'system.code_attempts': 'Too many failed attempts. Request a new code.',
  'system.unexpected': 'Something went wrong. Please try again shortly.',
  'system.validation': 'Check the information you entered and try again.',
  'system.not_found': 'The requested information is unavailable.',
  'system.forbidden': 'You do not have access to this action.',
  'system.referral_invalid': 'The invitation code is invalid.',
  'system.referral_self': 'You cannot use your own invitation code.',
  'system.too_many_requests': 'Too many requests. Wait a moment and try again.',
  'common.ok': 'OK',
  'common.new': 'New',
  'referral.not_available_title': 'Referral not available',
  'referral.not_available_message': 'This referral link cannot be applied because you are already logged in. Referral rewards are only available for new accounts created using a referral link.',
  'upload_bill.flash_auto': 'Auto',
  'upload_bill.flash_on': 'On',
  'upload_bill.flash_off': 'Off',
  'upload_bill.submitted_success': 'Bill submitted successfully.',
  'validation.phone_invalid': 'Enter a valid phone number',
  'support.hero_placeholder': 'Utility services',
  'profile.member_since': 'Member since @date',
  'duration.day_one': '1 day',
  'duration.days': '@count days',
  'duration.month_one': '1 month',
  'duration.months': '@count months',
  'offer.duration_indefinite': 'Open-ended',
  'offer.no_binding': 'No lock-in period',
  'offer.market_fixed': 'Fixed price',
  'offer.market_variable': 'Variable price',
  'offer.market_indexed': 'Indexed price',
  'request.form.target_business': 'Business',
  'request.form.target_residential': 'Residential',
  'request.form.documents_upload_failed': 'One or more identity documents could not be uploaded. Please try again.',
  'agreements.valid_from': 'From @date',
  'notifications.channel_name': 'VYZI notifications',
  'notifications.channel_description': 'Updates on your bills, offers and requests',
  'common.search': 'Search',
  'api_field.email': 'Email',
  'api_field.password': 'Password',
  'api_field.confirmPassword': 'Confirm password',
  'api_field.currentPassword': 'Current password',
  'api_field.newPassword': 'New password',
  'api_field.firstName': 'First name',
  'api_field.lastName': 'Last name',
  'api_field.phone': 'Phone number',
  'api_field.codiceFiscale': 'Tax code',
  'api_field.partitaIva': 'VAT number',
  'api_field.companyName': 'Company name',
  'api_field.companyType': 'Company type',
  'api_field.legalRepresentative': 'Legal representative',
  'api_field.atecoCode': 'ATECO code',
  'api_field.jobRole': 'Role',
  'api_field.pecEmail': 'PEC',
  'api_field.role': 'Account type',
  'api_field.referralCode': 'Referral code',
  'api_field.code': 'Verification code',
  'api_field.acceptedTerms': 'Terms acceptance',
  'api_field.iban': 'IBAN',
  'api_field.ibanHolderFirstName': 'Account holder first name',
  'api_field.ibanHolderLastName': 'Account holder last name',
  'api_field.ibanHolderTaxCode': 'Account holder tax ID',
  'api_field.podNumber': 'POD code',
  'api_field.pdrNumber': 'PDR code',
  'api_field.meterNumber': 'Meter number',
  'api_field.address': 'Address',
  'api_field.streetAddress': 'Street address',
  'api_field.city': 'City',
  'api_field.province': 'Province',
  'api_field.postalCode': 'Postcode',
  'api_field.country': 'Country',
  'api_field.supplyStreet': 'Supply street',
  'api_field.supplyStreetNumber': 'Supply street number',
  'api_field.supplyCity': 'Supply city',
  'api_field.supplyProvince': 'Supply province',
  'api_field.supplyPostalCode': 'Supply postcode',
  'api_field.residentialStreet': 'Residential street',
  'api_field.residentialStreetNumber': 'Residential street number',
  'api_field.residentialCity': 'Residential city',
  'api_field.residentialProvince': 'Residential province',
  'api_field.residentialPostalCode': 'Residential postcode',
  'api_field.shippingStreet': 'Shipping street',
  'api_field.shippingStreetNumber': 'Shipping street number',
  'api_field.shippingCity': 'Shipping city',
  'api_field.shippingProvince': 'Shipping province',
  'api_field.shippingPostalCode': 'Shipping postcode',
  'api_field.invoiceEmail': 'Invoice email',
  'api_field.paymentMethod': 'Payment method',
  'api_field.invoiceDelivery': 'Invoice delivery',
  'api_field.language': 'Language',
  'api_field.contactPreference': 'Contact preference',
  'api_field.subject': 'Subject',
  'api_field.message': 'Message',
  'api_field.description': 'Description',
  'api_field.topicId': 'Topic',
  'api_field.billType': 'Bill type',
  'api_field.utilityType': 'Utility type',
  'api_field.documentType': 'Document type',
  'api_field.fileIds': 'Documents',
  'api_field.offerId': 'Offer',
  'api_field.selectedOfferId': 'Offer',
  'api_field.notes': 'Notes',
};
