final Map<String, String> itIT = {
  // ==================== AUTH FLOW ====================
  'auth.login.title': 'Accedi al tuo account',
  'auth.login.email_label': 'Indirizzo Email *',
  'auth.login.email_hint': 'Inserisci il tuo indirizzo email',
  'auth.login.email_error': 'Inserisci un\'email valida',
  'auth.login.password_label': 'Password *',
  'auth.login.password_hint': '••••••••••',
  'auth.login.password_error': 'Minimo 8 caratteri',
  'auth.login.forgot_password': 'Hai dimenticato la password?',
  'auth.login.reset_now': 'Reimposta ora',
  'auth.login.button': 'Accedi',
  'auth.login.divider': 'Oppure accedi con',
  'auth.login.facebook': 'Accedi con Facebook',
  'auth.login.apple': 'Accedi con Apple',
  'auth.login.google': 'Accedi con Google',
  'auth.login.no_account': 'Non hai un account?',
  'auth.login.signup': 'Registrati ora',
  'auth.login.error.failed': 'Login fallito. Riprova.',
  'auth.login.error.invalid_credentials': 'Email o password non valida',
  'auth.login.error.suspended': 'Il tuo account è stato sospeso. Contatta l\'assistenza.',
  'auth.login.error.not_verified': 'Email non verificata. Completa la verifica del codice.',
  'auth.login.error.social_failed': 'Accesso social fallito. Riprova.',
  'auth.login.error.no_social_account':
      'Nessun account per questo profilo. Scegli il tipo di account per registrarti.',

  // Social sign-in (Google / Facebook / Apple)
  'auth.social.error.cancelled': 'Accesso annullato.',
  'auth.social.error.generic': 'Accesso social fallito. Riprova.',
  'auth.social.error.interrupted': 'Accesso interrotto. Riprova.',
  'auth.social.error.configuration':
      'Accesso social non disponibile: configurazione non valida. Contatta l\'assistenza.',
  'auth.social.error.no_firebase_token':
      'Impossibile ottenere il token di autenticazione. Riprova.',
  'auth.social.error.account_exists':
      'Esiste già un account con questa email, registrato con un altro metodo di accesso.',
  'auth.social.error.provider_disabled':
      'Questo metodo di accesso non è abilitato. Contatta l\'assistenza.',
  'auth.social.error.user_disabled': 'Questo account è stato disabilitato.',
  'auth.social.error.network':
      'Connessione non disponibile. Controlla la rete e riprova.',

  'auth.signup.title': 'Crea un account',
  'auth.signup.first_name_label': 'Nome *',
  'auth.signup.first_name_hint': 'Inserisci il tuo nome',
  'auth.signup.last_name_label': 'Cognome *',
  'auth.signup.last_name_hint': 'Inserisci il tuo cognome',
  'auth.signup.email_label': 'Indirizzo Email *',
  'auth.signup.email_hint': 'Inserisci il tuo indirizzo email',
  // Un account business si registra con la propria PEC. Nulla qui distingue
  // un indirizzo certificato da uno ordinario - sono stringhe identiche -
  // quindi e' l'etichetta a dire all'azienda quale dei due inserire.
  'auth.signup.phone_label': 'Numero di telefono (opzionale)',
  'auth.signup.company_name_label': 'Nome dell\'Azienda *',
  'auth.signup.company_name_hint': 'Inserisci il nome dell\'azienda',
  'auth.signup.company_name_error': 'Il nome dell\'azienda è obbligatorio',
  'auth.signup.company_name_short': 'Il nome dell\'azienda è troppo corto',
  'auth.signup.vat_label': 'Partita IVA *',
  'auth.signup.vat_hint': '11 cifre, senza spazi',
  'auth.signup.vat_required': 'La partita IVA è obbligatoria',
  'auth.signup.vat_invalid': 'Inserisci una Partita IVA valida: 11 cifre, di cui l\'ultima deve corrispondere alle altre.',
  'auth.signup.password_label': 'Password *',
  'auth.signup.password_hint': '••••••••••',
  'auth.signup.password_lowercase': 'Deve contenere almeno una lettera minuscola',
  'auth.signup.password_uppercase': 'Deve contenere almeno una lettera maiuscola',
  'auth.signup.password_number': 'Deve contenere almeno un numero',
  'auth.signup.password_special': 'Deve contenere almeno un carattere speciale',
  'auth.signup.confirm_password_label': 'Conferma Password *',
  'auth.signup.confirm_password_hint': '••••••••••',
  'auth.signup.password_mismatch': 'Le password non corrispondono',
  'auth.signup.accept_prefix': 'Accetto i ',
  'auth.signup.terms_link': 'Termini di Servizio',
  'auth.signup.privacy_link': 'l\'Informativa sulla Privacy',
  'auth.signup.list_separator': ', ',
  'auth.signup.list_conjunction': ' e ',
  'auth.signup.terms_required': 'Devi accettare i Termini di Servizio e l\'Informativa sulla Privacy per procedere.',
  'auth.signup.button': 'Registrati',
  'auth.signup.divider': 'Oppure accedi con',
  'auth.signup.have_account': 'Hai già un account? ',
  'auth.signup.login': 'Accedi',
  'auth.signup.error.failed': 'Registrazione fallita. Riprova.',
  'auth.signup.error.email_exists': 'Email già registrata',
  'auth.signup.error.vat_exists': 'Questa partita IVA è già registrata su un altro account',

  'auth.otp.title': 'Verifica codice',
  'auth.otp.button': 'Verifica codice',
  'auth.otp.resend': 'Invia di nuovo il codice',
  'auth.otp.error_incomplete': 'Inserisci il codice completo',

  'auth.forgot_password.title': 'Password Dimenticata',
  'auth.forgot_password.email_label': 'Indirizzo Email *',
  'auth.forgot_password.email_hint': 'Inserisci il tuo indirizzo email',
  'auth.forgot_password.email_error': 'Inserisci un\'email valida',
  'auth.forgot_password.button': 'Invia il codice',

  'auth.reset_password.title': 'Reimposta Password',
  'auth.reset_password.password_label': 'Password *',
  'auth.reset_password.password_hint': '••••••••••',
  'auth.reset_password.password_error': 'Minimo 6 caratteri',
  'auth.reset_password.confirm_label': 'Conferma Password *',
  'auth.reset_password.confirm_hint': '••••••••••',
  'auth.reset_password.mismatch': 'Le password non corrispondono',
  'auth.reset_password.button': 'Reimposta Password',

  'auth.success.title': 'Tutto pronto!',
  'auth.success.message': 'Password aggiornata\ncon successo',
  'auth.success.button': 'Torna al login',

  // ==================== HOME SCREEN ====================
  'home.header.greeting': 'Ciao, là! 👋',
  'home.header.subtitle': 'Pronto a risparmiare sulle tue utenze?',
  'home.header.onboarding_greeting': 'Ciao! 👋',
  'home.header.onboarding_subtitle': 'Prendi il controllo delle tue utenze oggi',
  'home.upload_section.title': 'Carica la tua Prima\nBolletta',
  'home.upload_section.subtitle': 'Lasciaci analizzare il tuo piano\nattuale e trovare offerte migliori',
  'home.upload_section.button': 'Inizia a Risparmiare',
  'home.summary.savings_title': 'Risparmio potenziale',
  'home.summary.savings_subtitle': 'all\'anno',
  'home.summary.utilities_title': 'Utenze attive',
  'home.summary.utilities_subtitle': 'gestite',
  'home.how_it_works.title': 'Come Funziona',
  'home.how_it_works.step1_title': 'Carica la tua Bolletta',
  'home.how_it_works.step1_desc': 'Scatta una foto alla tua bolletta o carica direttamente un PDF dall\'app.',
  'home.how_it_works.step2_title': 'Analizziamo e proponiamo',
  'home.how_it_works.step2_desc': 'Il team VYZI analizza la tua situazione attuale. Riceverai una notifica con le offerte più adatte.',
  'home.how_it_works.step3_title': 'Scegli e attiva',
  'home.how_it_works.step3_desc': 'Confronta le offerte selezionate e scegli quella che preferisci. Noi gestiamo l\'attivazione.',
  'home.utilities_section.title': 'Le tue Utenze',
  'home.utilities_section.view_all': 'Visualizza Tutto',
  'home.utilities_section.address_missing': 'Indirizzo non disponibile',
  'home.actions.title': 'Cosa vuoi fare oggi?',
  'home.actions.change_supplier': 'Cambia fornitore',
  'home.actions.change_supplier_desc': 'Confronta le offerte e scopri se puoi risparmiare.',
  'home.actions.transfer': 'Voltura',
  'home.actions.transfer_desc': 'Cambio intestatario e fornitore in un’unica richiesta.',
  'home.actions.activate': 'Attiva una nuova utenza',
  'home.actions.activate_desc': 'Richiedi l’attivazione di luce o gas.',
  'home.actions.activate_badge': 'Nuovo',
  'home.actions.check_invoice': 'Controlla la bolletta',
  'home.actions.check_invoice_desc': 'Verifica se la tua offerta è ancora conveniente.',

  // ==================== PROFILE SCREEN ====================
  'profile.title': 'Profilo',
  'profile.subtitle': 'Gestisci le impostazioni del tuo account',
  'profile.account_type_personal': 'Privato',
  'profile.account_type_business': 'Azienda',
  'profile.section.account': 'Gestione Account',
  'profile.section.invite': 'Invita e Premi',
  'profile.section.other': 'Altro',
  'profile.menu.personal_data': 'Dati Personali',
  'profile.menu.personal_data_desc': 'Modifica le informazioni del tuo profilo',
  'profile.menu.utilities': 'Le tue utenze',
  'profile.menu.utilities_desc': 'Visualizza i servizi attivi',
  'profile.menu.requests': 'Le tue richieste',
  'profile.menu.requests_desc': 'Segui i tuoi passaggi',
  'profile.menu.invite': 'Invita e Guadagna',
  'profile.menu.invite_desc': 'Condividi il tuo link e guadagna 10',
  'profile.menu.support': 'Supporto',
  'profile.menu.support_desc': 'Ricevi aiuto e contattaci',
  'profile.menu.agreements': 'Convenzioni',
  'profile.menu.agreements_desc': 'Sconti esclusivi dei partner',
  'profile.menu.more': 'Altro',
  'profile.menu.more_desc': 'Privacy Legale',
  'profile.menu.logout': 'Disconnetti',
  'profile.logout.confirm': 'Sei sicuro di voler uscire?',
  'profile.logout.cancel': 'Annulla',
  'profile.settings.privacy': 'Informativa sulla Privacy',
  'profile.settings.terms': 'Termini e Condizioni',
  'profile.settings.about': 'Su VYZI',
  'profile.settings.faq': 'Faq',
  'profile.settings.language': 'Lingua',
  'profile.settings.language_italian': 'Italiano',
  'profile.settings.language_english': 'English',
  'profile.settings.delete_account': 'Elimina Account',
  'profile.settings.delete_confirm_title': 'Elimina Account',
  'profile.settings.delete_confirm_msg': 'Sei sicuro di voler eliminare il tuo account? Questa azione è irreversibile.',
  'profile.settings.delete_confirm_cancel': 'Annulla',
  'profile.settings.delete_confirm_delete': 'Elimina',
  'profile.settings.title': 'Impostazioni',

  // ==================== SUPPORT SCREEN ====================
  'support.title': 'Supporto',
  'support.greeting': 'Ciao, come possiamo aiutarti?',
  'support.subtitle': 'Cerca le nostre guide o contatta il supporto tecnico.',
  'support.form.tab.technical': 'Supporto Tecnico',
  'support.form.tab.billing': 'Fatturazione e Pagamenti',
  'support.form.topic_label': 'Argomento',
  'support.form.message_label': 'Messaggio',
  'support.form.message_hint': 'Descrivi il tuo problema o domanda...',
  'support.form.submit': 'Invia Richiesta',

  // ==================== NAVBAR ====================
  'navbar.home': 'Home',
  'navbar.utilities': 'Utenze',
  'navbar.request': 'Richieste',
  'navbar.profile': 'Profilo',

  // ==================== COMMON ====================
  'common.error': 'Errore',
  'common.success': 'Successo',
  'common.loading': 'Caricamento...',
  'common.no_data': 'Nessun dato disponibile',
  'common.try_again': 'Riprova',
  'common.cancel': 'Annulla',
  'common.confirm': 'Conferma',
  'common.close': 'Chiudi',
  'common.back': 'Indietro',
  'common.no_internet': 'Nessuna connessione Internet',
  'common.no_internet_message': 'Nessuna connessione Internet. Riprova.',
  'common.oops': 'Ops!',
  'common.retry': 'Riprova',
  'common.server_error': 'Errore del server',
  'common.unexpected_error': 'Si è verificato un errore imprevisto',
  'common.failed_to_load': 'Impossibile caricare i dati',
  'common.save': 'Salva',
  'common.got_it': 'Capito',
  'common.per_month': '/mese',

  // ==================== EMAIL BILL ====================
  'home.email_bill.confirm_same_email': 'Assicurati di usare la stessa email con cui hai creato il tuo account su VYZI.',
  'home.email_bill.note1': 'Se invii foto della bolletta, allega almeno le prime 3 pagine.',
  'home.email_bill.note2': 'Puoi inviare anche eventuali condizioni economiche o altri documenti utili per l’analisi.',
  'home.email_bill.button': 'Ho inviato la bolletta',
  'home.email_bill.back': 'Torna indietro',
  'home.email_bill.go_to_requests': 'Vai alle Richieste',
  'home.email_bill.back_to_home': 'Torna alla Home',
  'home.email_bill.title': 'Invia la tua bolletta via email',
  'home.email_bill.instructions': 'Istruzioni',
  'home.email_bill.instruction_text': 'Puoi inviarci la bolletta quando preferisci, allegandola all’indirizzo qui sotto.',
  'home.email_bill.email_label': 'Indirizzo email',
  'home.email_bill.copy': 'Copia',

  // ==================== BILLS ====================
  'bills.title': 'Le Mie Bollette',
  'bills.load_failed': 'Impossibile caricare le bollette',
  'bills.no_bills_found': 'Nessuna bolletta trovata',
  'bills.list.amount': 'Importo',
  'bills.list.period': 'Periodo',
  'bills.list.date': 'Data',
  'bills.detail.title': 'Dettagli bolletta',
  'bills.detail.info': 'Informazioni Bolletta',
  'bills.detail.contract_banner.ready_title': 'Contratto Pronto da Firmare',
  'bills.detail.contract_banner.ready_subtitle': 'Tocca per vedere come firmare il contratto',
  'bills.detail.contract_banner.in_activation_title': 'Utenza in Attivazione',
  'bills.detail.contract_banner.in_activation_subtitle': 'Tocca per vedere i dettagli del passaggio',
  'bills.detail.contract_banner.active_title': 'Contratto Attivo',
  'bills.detail.contract_banner.active_subtitle': 'Tocca per vedere il tuo servizio attivo',
  'bills.detail.contract_banner.preparing_title': 'Contratto in Preparazione',
  'bills.detail.contract_banner.preparing_subtitle': 'Tocca per seguire lo stato',
  'bills.detail.verification_banner.title': 'Verifica Richiesta',
  'bills.detail.verification_banner.subtitle': 'Tocca per inviare i documenti richiesti',
  'case.document.banner.title': 'Documento da sostituire',
  'case.document.banner.subtitle': 'Tocca per caricarne uno nuovo',
  'case.document.rejection.expired': 'Scaduto',
  'case.document.rejection.unreadable': 'Non leggibile',
  'case.document.rejection.incomplete': 'Incompleto',
  'case.document.rejection.wrong_document': 'Documento errato',
  'case.document.rejection.other': 'Non accettabile',
  'case.document.replace.title': 'Nuovo documento d\'identità',
  'case.document.replace.intro': 'Non abbiamo potuto accettare il documento qui sotto. Caricane una versione valida: la verificheremo di nuovo e ti avviseremo.',
  'case.document.replace.reason': 'Motivo',
  'case.document.replace.submit': 'Invia il nuovo documento',
  'case.document.replace.sent_title': 'Documento inviato',
  'case.document.replace.sent_body': 'Lo verificheremo al più presto.',
  'bills.detail.recommended_offers': 'Offerte Consigliate',
  'bills.detail.progress.title': 'Avanzamento',
  'bills.detail.progress.upload': 'Caricamento',
  'bills.detail.progress.verification': 'Verifica',
  'bills.detail.progress.offers': 'Offerte',
  'bills.detail.progress.contract': 'Contratto',
  'bills.detail.progress.activation': 'In Attivazione',
  'bills.detail.progress.activated': 'Attivata',
  'bills.detail.hero.done_title': 'Il tuo Passaggio è Completato',
  'bills.detail.hero.done_desc': 'La tua nuova fornitura è attiva. Non serve altro da parte tua.',
  'bills.detail.hero.attention_title': 'Questa Richiesta Richiede Attenzione',
  'bills.detail.timeline.sent_title': 'Inviata',
  'bills.detail.timeline.sent_subtitle': 'Abbiamo ricevuto la tua richiesta.',
  'bills.detail.timeline.analyzed_title': 'Analizzata',
  'bills.detail.timeline.analyzed_subtitle': 'Abbiamo verificato i dati della tua bolletta.',
  'bills.detail.timeline.contract_signed_title': 'Contratto firmato',
  'bills.detail.timeline.contract_signed_subtitle': 'Il contratto con il nuovo fornitore è stato firmato.',
  'bills.detail.timeline.in_activation_title': 'In attivazione',
  'bills.detail.timeline.in_activation_subtitle': 'Il nuovo fornitore sta completando l’attivazione.',
  'bills.detail.timeline.activated_title': 'Attivata',
  'bills.detail.timeline.activated_subtitle': 'La nuova fornitura è attiva.',
  'bills.detail.timeline.ko_title': 'KO / Terminata',
  'bills.detail.timeline.ko_subtitle': 'Questa richiesta è stata chiusa',

  // ==================== MY UTILITIES ====================
  'my_utility.title': 'Le tue utenze',
  'my_utility.subtitle': 'Gestisci le tue utenze attive',
  'my_utility.upload_button': 'Carica la bolletta',
  'my_utility.no_utilities': 'Nessuna utenza attiva',
  'utility.pod_label': 'POD',
  'utility.active_since': 'Attivo Dal',
  'utility.offer_type': 'Tipo di Offerta',
  'utility.address': 'Indirizzo',
  'utility.meter_number': 'Numero Contatore',
  'utility.send_email': 'Invia Email',
  'utility.open_ticket': 'Apri Ticket',
  'utility.open_ticket_desc': 'Ricevi aiuto dal supporto app',
  'utility.website': 'Sito Web',
  'utility.file_selected': 'File selezionato',
  'utility.scanned': 'Scansionato',
  'utility.details_title': 'Dettagli Utenza',
  'utility.active_offer_badge': 'OFFERTA ATTIVA',
  'utility.status.activated': 'Attivo',
  'utility.status.awaiting_activation': 'In Attivazione',
  'utility.active_offer': 'Offerta Attiva',
  'utility.offer_name': 'Nome Offerta',
  'utility.service_type': 'Tipo di Servizio',
  'utility.supply_info': 'Informazioni Fornitura',
  'utility.pod_code': 'CODICE POD',
  'utility.copy': 'Copia',
  'utility.material_price': 'PREZZO MATERIA',
  'utility.spread_over_index': 'SPREAD SU @index',
  'utility.activation': 'ATTIVAZIONE',
  'utility.activation_planned': 'ATTIVAZIONE PREVISTA',
  'utility.annual_consumption': 'CONSUMO ANNUALE',
  'utility.fixed_fee': 'Costo Fisso',
  'utility.monthly_estimate': 'Stima Mensile',
  'utility.contract_duration': 'Durata',
  'utility.expiry': 'Scadenza',
  'utility.green_energy': 'Energia Verde',
  'utility.contract_number': 'Numero Contratto',
  'utility.copied': 'Copiato negli appunti',
  'utility.awaiting_activation_badge': 'IN ATTIVAZIONE',
  'utility.error_load': 'Non siamo riusciti a caricare questo servizio.',
  'utility.retry': 'Riprova',
  'utility.contact_support': 'Contatta il Supporto',
  'utility.about_supplier': 'Chi è @name',
  'utility.faq': 'Domande Frequenti',

  // ==================== ONBOARDING ====================
  'onboarding.next': 'Avanti',
  'onboarding.skip': 'Salta',

  // ==================== REQUEST ====================
  'request.offers.load_failed': 'Impossibile caricare le offerte',
  'request.bills.load_failed': 'Impossibile caricare le richieste',
  'request.status.sent': 'Inviata',
  'request.status.sent_desc': 'Richiesta ricevuta con successo',
  'request.status.analyzing': 'Analisi in corso',
  'request.status.analyzing_desc': 'I nostri esperti stanno verificando i dati',
  'request.status.contract': 'Contratto',
  'request.status.contract_desc': 'Conferma finale del passaggio',
  'request.title': 'Richieste',
  'request.go_to_details': 'Vai ai dettagli e procedi',
  'request.success.title': 'Richiesta Inviata con Successo',
  'request.success.subtitle': 'Abbiamo ricevuto la tua richiesta di\nattivazione.',
  'request.success.what_happens': 'Cosa succede ora',
  'request.success.step1': 'Verifichiamo i dati inseriti',
  'request.success.step1_desc': 'I nostri sistemi automatizzati verificano l\'accuratezza delle tue informazioni.',
  'request.success.step2': 'Prepariamo la pratica',
  'request.success.step2_desc': 'Ci coordiniamo con i fornitori di servizi per avviare la tua richiesta.',
  'request.success.step3': 'Il contratto sarà disponibile entro 24 ore',
  'request.success.step3_desc': 'La tua documentazione sarà generata e inviata per la firma.',
  'request.success.info_title': 'Come completerai la richiesta?',
  'request.success.info_desc': 'Riceverai le istruzioni per firmare il contratto via SMS, email o link dedicato, in base al fornitore scelto.',
  'request.success.view_request': 'Visualizza la Mia Richiesta',
  'request.success.back_home': 'Torna alla Home',
  'request.tab.your_offers': 'Le tue offerte',
  'request.tab.my_requests': 'Le tue richieste',

  // ==================== OFFER DETAILS ====================
  'offer.contract_term': 'Vincolo contrattuale',
  'offer.price_type': 'Tipo di prezzo',
  'offer.energy_price': 'Prezzo energia',
  'offer.fixed_costs': 'Costi fissi materia energia',
  'offer.contract_duration': 'Durata del contratto',
  'offer.payment_method': 'Metodo di pagamento',
  'offer.about_supplier': 'Informazioni sul Fornitore',

  // ==================== COMPLETE REQUEST FORM ====================
  'request.offer.green_energy': 'Energia Verde',
  'request.offer.green_offer': 'Offerta Verde',
  'request.offer.annual_savings': 'Risparmio Annuale',
  'request.form.readonly_summary': 'Riepilogo in sola lettura da Bolletta/Profilo',
  'request.form.address_verified': 'Indirizzo verificato',
  'request.form.delivery_address': 'Indirizzo di fornitura',
  // I cinque campi raccolti per ogni indirizzo (fornitura, residenza, spedizione)
  'request.form.address': 'Indirizzo',
  'request.form.street_number': 'Numero Civico',
  'request.form.city': 'Città',
  'request.form.postal_code': 'CAP',
  'request.form.province': 'Provincia',
  'request.form.new_residential_address': 'Nuovo Indirizzo Residenziale',
  'request.form.new_registered_office': 'Nuova Sede Legale',
  'request.form.payment_preference': 'Seleziona come preferisci pagare',
  'request.form.choose_payment_method': 'Scegli il metodo di pagamento',
  'request.payment.sdd_title': 'Addebito diretto (SDD)',
  'request.payment.sdd_subtitle': 'Pagamento automatico dal tuo conto corrente.',
  'request.payment.postal_bill_title': 'Bollettino postale',
  'request.payment.postal_bill_subtitle': 'Riceverai il bollettino per pagare la bolletta.',
  'request.form.holder_info': 'Informazioni titolare',
  'request.invoice.digital_title': 'Fattura digitale',
  'request.invoice.digital_subtitle': 'Ricevi la bolletta via email.',
  'request.invoice.paper_title': 'Fattura cartacea',
  'request.invoice.paper_subtitle': 'Ricevi la bolletta per posta.',
  'request.form.shipping_match_question': 'L\'indirizzo di spedizione corrisponde all\'indirizzo di fornitura?',
  'request.form.almost_done': 'Quasi fatto!',
  'request.form.activate_offer': 'Attiva Offerta',
  'request.form.no_bill_warning': 'Carica prima una bolletta per attivare questa offerta. Vai alla sezione Bollette per caricare la tua bolletta energetica.',
  'request.form.scan_document': 'Scansiona Documento',
  'request.form.align_document': 'Allinea il documento nella cornice',
  'request.form.supported_formats': 'Sono supportati anche codici QR e codici a barre',

  // ==================== SUPPORT CALLBACK ====================
  'support.callback.title': 'Richiedi Chiamata',
  'support.callback.intro_text': 'Ti chiameremo all\'orario preferito per discutere la tua richiesta.',
  'support.callback.phone_label': 'Numero di Telefono',
  'support.callback.phone_hint': 'Inserisci il tuo numero di telefono',
  'support.callback.time_slot_label': 'Fascia Oraria Preferita',
  'support.callback.select_time': 'Seleziona un orario',
  'support.callback.morning': 'Mattina (09:00 – 12:00)',
  'support.callback.afternoon': 'Pomeriggio (12:00 – 15:00)',
  'support.callback.evening': 'Sera (15:00 – 18:00)',
  'support.callback.note': 'Nota: Il nostro team risponde solitamente entro 2-4 ore lavorative durante i giorni feriali (Lun-Ven).',
  'support.callback.request_button': 'Richiedi Chiamata',
  'support.other_contact_methods': 'Altri modi per contattarci',
  'support.default_topic': 'Richiesta Fatturazione',

  // ==================== SUPPORT CATEGORIES ====================
  'support.getting_started': 'Come iniziare',
  'support.getting_started_desc': 'Scopri come utilizzare l\'app passo dopo passo',
  'support.utilities_setup': 'Utilità di Configurazione',
  'support.utilities_setup_desc': 'Gestisci l\'app e configura le tue utilità',
  'support.bills': 'Fatture',
  'support.bills_desc': 'Carica e controlla le tue fatture',
  'support.contact_us': 'Richiedi assistenza',
  'support.contact_us_desc': 'Apri un ticket e ricevi aiuto',
  'support.my_requests': 'Le mie richieste',
  'support.my_requests_desc': 'Visualizza lo storico delle tue richieste',

  // ==================== SUPPORT FORM ====================
  'support.form.intro': 'Hai bisogno di aiuto? Seleziona un argomento e descrivi la tua richiesta. Il nostro team specializzato risponderà il prima possibile.',
  'support.form.select_topic': 'Seleziona un argomento',
  'support.form.subject_label': 'Oggetto',
  'support.form.subject_hint': 'Breve descrizione della tua richiesta...',
  'support.form.default_topic': 'Richiesta Fatturazione',
  'support.form.topic.billing_question': 'Domanda Fatturazione',
  'support.form.topic.technical_issue': 'Problema Tecnico',
  'support.form.topic.switching_process': 'Processo di Passaggio',
  'support.form.topic.contact_question': 'Domanda Contatto',
  'support.form.topic.account_management': 'Gestione Account',
  'support.form.topic.other': 'Altro',
  'support.form.validation.topic': 'Seleziona un argomento',
  'support.form.validation.subject': 'Inserisci un oggetto',
  'support.form.validation.message': 'Inserisci un messaggio',
  'support.form.success': 'La tua richiesta è stata inviata con successo!',
  'support.form.success_title': 'Richiesta Inviata!',
  'support.form.success_subtitle': 'Abbiamo ricevuto il tuo messaggio e risponderemo entro 24 ore.',
  'support.form.error': 'Invio della richiesta fallito. Riprova.',
  'support.featured_label': 'ARTICOLO IN EVIDENZA',
  'support.featured_title': '5 consigli per ridurre la tua fattura del 20%',
  'support.contact.phone_label': 'Telefono',
  'support.contact.email_label': 'Email',
  'support.contact.hours_label': 'Orari',
  'support.contact.hours_value': 'Lun-Ven, 09:00 – 18:00',

  // ==================== SUPPORT TICKETS ====================
  'support.tickets.empty': 'Nessuna richiesta di supporto',
  'support.tickets.status.open': 'Aperto',
  'support.tickets.status.in_progress': 'In Corso',
  'support.tickets.status.resolved': 'Risolto',
  'support.tickets.status.closed': 'Chiuso',
  'support.ticket_detail.title': 'Dettaglio Ticket',
  'support.ticket_detail.send_hint': 'Scrivi un messaggio...',
  'support.ticket_detail.closed_notice': 'Questo ticket è stato chiuso e non accetta più messaggi.',
  'support.ticket_detail.today': 'Oggi',
  'support.ticket_detail.yesterday': 'Ieri',

  // Ticket Info Screen
  'support.ticket_info.title': 'Dettagli Ticket',
  'support.ticket_info.conversation': 'Conversazione',
  'support.ticket_info.messages': 'messaggi',
  'support.ticket_info.subject': 'Oggetto',
  'support.ticket_info.topic': 'Argomento',
  'support.ticket_info.priority': 'Priorità',
  'support.ticket_info.priority.low': 'Basso',
  'support.ticket_info.priority.medium': 'Medio',
  'support.ticket_info.priority.high': 'Alto',
  'support.ticket_info.priority.urgent': 'Urgente',
  'support.ticket_info.created': 'Creato',
  'support.ticket_info.updated': 'Ultimo aggiornamento',
  'support.ticket_info.resolved': 'Risolto',
  'support.ticket_info.closed': 'Chiuso',
  'support.ticket_info.original_message': 'Messaggio originale',
  'support.ticket_info.not_found': 'Ticket non trovato',
  'support.ticket_info.closed_banner': 'Questo ticket è stato chiuso.',

  // ==================== PROFILE EXTRAS ====================
  'profile.account_type_label': 'Tipo di account',
  'profile.invite.link_shared': 'Link condiviso!',
  'profile.invite.title': 'Invita i tuoi amici',
  'profile.invite.hero_title': 'Condividi VYZI, guadagnate entrambi',
  'profile.invite.hero_desc': 'Invita i tuoi amici a usare VYZI. Se una pratica va a buon fine, ricevete entrambi un buono Amazon da 10 €.',
  'profile.invite.link_label': 'Link di invito personale',
  'profile.invite.copy': 'Copia',
  'profile.invite.share_link': 'Condividi il link',
  'profile.invite.you_earn': 'Tu ricevi',
  'profile.invite.you_earn_when': 'Buono Amazon dopo l’attivazione della pratica del tuo amico.',
  'profile.invite.friend_gets': 'Il tuo amico riceve',
  'profile.invite.friend_gets_when': 'Buono Amazon dopo l’attivazione della sua pratica.',
  'profile.invite.stats_title': 'I tuoi inviti',
  'profile.invite.invites_sent': 'Inviti inviati',
  'profile.invite.invites_sent_desc': 'Link condivisi',
  'profile.invite.completed': 'Inviti attivati',
  'profile.invite.completed_desc': 'Pratiche andate a buon fine',
  'profile.invite.earnings_title': 'Guadagni totali',
  'profile.invite.earnings_status': 'DISPONIBILE',
  'profile.invite.earnings_type': 'Totale in buoni Amazon',
  'profile.invite.tip': 'Suggerimento',
  'profile.invite.tip_text': 'Condividi il tuo link con amici e familiari per guadagnare di più.',
  'profile.invite.share_text': 'Usa il mio link referral per risparmiare sulle bollette',

  // ==================== EMAIL BILL RECEIVED ====================
  'home.email_bill_received.title': 'Richiesta Creata!',
  'home.email_bill_received.subtitle': 'La tua richiesta è stata creata con successo.\nIl nostro team elaborerà la tua bolletta una volta ricevuta via email.',
  'home.email_bill_received.analysis_in_progress': 'Elaborazione della Richiesta',
  'home.email_bill_received.analysis_time_info': 'La verifica viene completata generalmente entro 24 ore lavorative. Ti aggiorneremo non appena sarà terminata.',

  // ==================== COMPLETE REQUEST FORM EXTRAS ====================
  'request.offer_details.price_formula': 'Prezzo Energia : PUN GME + \u20AC 0.01/KWh',
  'request.form.residential_matches_delivery': 'L’indirizzo di residenza corrisponde all’indirizzo di fornitura?',
  // "Fornitura", non "consegna": è l'indirizzo in cui l'energia viene fornita,
  // ed è il termine usato dal resto del modulo.
  'request.form.registered_office_matches_delivery':
      'La sede legale corrisponde all\'indirizzo di fornitura?',
  'request.form.address_yes_same': 'Sì, è lo stesso',
  'request.form.address_no_different': 'No, è diverso',
  'request.form.no_selection_info': 'Inserisci qui sotto il tuo indirizzo di residenza.',
  'request.form.no_selection_info_business':
      'Inserisci qui sotto la sede legale dell\'azienda.',
  'request.form.id_document_instruction': 'Carica un documento di identità valido per completare la richiesta. Puoi utilizzare carta d’identità, patente o passaporto. Carica fronte e retro, quando previsti. Puoi caricarli in un unico file oppure come foto o file separati.',
  'request.form.upload_file_button': 'Carica documento',
  'request.form.upload_formats': 'PDF o foto da galleria/file',
  'request.form.take_photo_button': 'Scatta foto',
  'request.form.take_photo_hint': 'Fronte e retro',
  'request.form.id_camera_title': 'Fotografa il documento',
  'request.form.files_selected': 'file selezionati',
  'request.form.scan_document_button': 'Scansiona Documento',
  'request.form.scan_with_camera': 'Scansiona con la fotocamera',
  'request.form.payment_method_title': 'Metodo di pagamento',
  'request.form.full_name_label': 'Nome completo',
  'request.form.tax_code_label': 'Codice fiscale',
  'request.form.first_name': 'Nome',
  'request.form.last_name': 'Cognome',
  'request.form.tax_code_error': 'Inserisci un Codice Fiscale valido (16 caratteri).',
  'request.form.tax_code_vat_not_accepted': 'La Partita IVA non è utilizzabile qui. Inserisci il Codice Fiscale del titolare (16 caratteri).',
  'request.form.tax_code_error_check': 'L\'ultimo carattere non corrisponde al resto del codice: dovrebbe essere @char.',
  'request.form.tax_code_required_hint': 'Per l\'addebito diretto è necessario un Codice Fiscale valido.',
  'request.form.vat_label': 'Partita IVA',
  'request.form.vat_error': 'Inserisci una Partita IVA valida: 11 cifre, di cui l\'ultima deve corrispondere alle altre.',
  'request.form.vat_tax_code_not_accepted': 'Il Codice Fiscale non è utilizzabile qui. Un\'azienda è identificata dalla sua Partita IVA (11 cifre).',
  'request.form.vat_required_hint': 'Per l\'addebito diretto è necessaria una Partita IVA valida.',
  'request.form.holder_tax_id_label': 'Codice Fiscale / Partita IVA del titolare',
  'request.form.holder_tax_id_error': 'Inserisci un Codice Fiscale valido (16 caratteri) o una Partita IVA valida (11 cifre).',
  'request.form.holder_first_name_required': 'Il nome del titolare è obbligatorio.',
  'request.form.holder_last_name_required': 'Il cognome del titolare è obbligatorio.',
  'request.form.contract_send_info': 'Una volta completata la richiesta, ti invieremo il contratto entro 24 ore lavorative per la firma.',
  'request.payment.sdd_subtitle_full': 'Pagamento automatico dal tuo conto corrente.',
  'request.payment.postal_bill_subtitle_full': 'Riceverai il bollettino per pagare la bolletta.',
  'request.invoice.destination_preview': 'La bolletta verrà inviata a:',
  'request.form.conform_address': 'Conferma Indirizzo',
  'request.form.complete_request_title': 'Completa la tua richiesta',
  'request.form.personal_info_title': 'Informazioni Personali',
  'request.form.edit': 'Modifica',
  'request.form.save_holder_details': 'Salva dati titolare',
  'request.form.edit_holder_details': 'Modifica dati titolare',
  'request.form.holder_details_saved': 'Dati salvati',
  'request.form.first_name_field': 'Nome',
  'request.form.last_name_field': 'Cognome',
  'request.form.email_field': 'Email',
  'request.form.phone_field': 'Telefono',
  'request.form.pod_number_field': 'Numero POD',
  // Il riepilogo di un account business: l'azienda e il suo titolare sono due
  // parti distinte del contratto, ciascuna con il proprio identificativo.
  'request.form.company_name_field': 'Ragione Sociale',
  'request.form.owner_first_name_field': 'Nome del titolare',
  'request.form.owner_last_name_field': 'Cognome del titolare',
  'request.form.owner_tax_code_field': 'Codice Fiscale del titolare',
  'request.form.pec_field': 'PEC',
  'request.form.company_name_required': 'La ragione sociale è obbligatoria',
  'request.form.vat_required': 'La Partita IVA è obbligatoria',
  'request.form.owner_first_name_required':
      'Il nome del titolare è obbligatorio',
  'request.form.owner_last_name_required':
      'Il cognome del titolare è obbligatorio',
  'request.form.pec_invalid': 'Inserisci un indirizzo PEC valido',
  'request.form.payment_method_info': 'Metodo di Pagamento: ',
  'request.form.compatibility_info': 'Compatibilità: Residenziale',
  'request.form.identity_verification_title': 'Verifica identità',
  'request.form.required': 'Obbligatorio',
  'request.form.identity_required_hint': 'Carica almeno un file per attivare l\'offerta.',
  'request.form.invoice_delivery_title': 'Metodo di invio fattura',
  'request.form.invoice_delivery_tip': 'Il nostro consiglio: scegli la fattura digitale per riceverla più rapidamente e senza ritardi di consegna.',
  'request.form.iban_same_as_contract': 'Sì, il titolare dell’IBAN coincide con l’intestatario del contratto.',
  'request.form.iban_label': 'IBAN',
  'request.form.iban_hint': 'Inserisci il tuo IBAN',
  'request.form.iban_error': 'Inserisci un IBAN italiano valido di 27 caratteri alfanumerici.',
  'request.form.iban_required_hint': 'Inserisci un IBAN valido per attivare l\'offerta.',
  'request.form.prefilled_email': 'Email precompilata dal tuo profilo',
  'request.form.email_for_invoice': 'Email per la fattura',
  'request.form.pec_for_invoice': 'PEC per la fattura',
  'request.form.yes': 'Sì',
  'request.form.no': 'No',
  'request.form.enter_shipping_address': 'Inserisci il tuo indirizzo di spedizione',
  'request.form.email_invoice_hint': 'Inserisci l\'email per la fattura',
  'request.form.pec_invoice_hint': 'Inserisci la PEC per la fattura',
  // Suggerimenti e messaggi di validazione degli indirizzi
  'request.form.street_hint': 'Inserisci la via',
  'request.form.street_number_hint': 'Es. 10',
  'request.form.city_hint': 'Inserisci la città',
  'request.form.postal_code_hint': 'Es. 20100',
  'request.form.province_hint': 'Inserisci la provincia',
  'request.form.street_required': 'Inserisci la via',
  'request.form.street_number_required': 'Inserisci il numero civico',
  'request.form.city_required': 'Inserisci la città',
  'request.form.postal_code_required': 'Inserisci il CAP',
  'request.form.postal_code_invalid': 'Il CAP deve essere di 5 cifre',
  'request.form.province_required': 'Inserisci la provincia',
  'request.form.address_missing': 'Indirizzo non disponibile',
  'request.form.complete_supply_address':
      'Completa l\'indirizzo di fornitura per attivare l\'offerta.',
  'request.form.address_required_hint':
      'Completa tutti gli indirizzi richiesti per attivare l\'offerta.',
  'request.form.shipping_match_required':
      'Seleziona dove vuoi ricevere le fatture cartacee',
  'request.form.first_name_required': 'Il nome è obbligatorio',
  'request.form.last_name_required': 'Il cognome è obbligatorio',
  'request.form.pod_number_required': 'Il numero POD è obbligatorio',
  'request.form.phone_required': 'Il numero di telefono è obbligatorio',
  'request.form.address_match_required': 'Seleziona se l\'indirizzo di residenza corrisponde all\'indirizzo di fornitura',
  'request.form.address_match_required_business':
      'Seleziona se la sede legale corrisponde all\'indirizzo di fornitura',
  'request.form.profile_update_failed':
      'Non è stato possibile salvare i tuoi dati personali. Riprova.',
  'request.form.invoice_email_error': 'Inserisci un indirizzo email valido',
  'request.form.invoice_email_required_hint':
      'Inserisci un indirizzo email valido per le tue fatture digitali.',

  // ==================== PERSONAL DATA ====================
  'personal_data.title': 'Dati Personali',
  'personal_data.subtitle': 'Aggiorna le informazioni del tuo account e come\nti contattiamo.',
  'personal_data.change_photo': 'Cambia foto',
  'personal_data.camera': 'Fotocamera',
  'personal_data.gallery': 'Galleria',
  'personal_data.first_name': 'Nome',
  'personal_data.last_name': 'Cognome',
  'personal_data.email': 'Email',
  'personal_data.phone': 'Numero di Telefono',
  'personal_data.tax_code': 'Codice Fiscale',
  'personal_data.pec_invalid': 'Inserisci un indirizzo PEC valido',
  'personal_data.privacy_title': 'Privacy Prima di Tutto',
  'personal_data.privacy_desc': 'I tuoi dati sono crittografati e gestiti secondo i nostri standard di protezione premium. Non condividiamo mai i tuoi dati personali con fornitori terzi senza il tuo consenso.',
  'personal_data.first_name_hint': 'Inserisci il tuo nome',
  'personal_data.last_name_hint': 'Inserisci il tuo cognome',
  'personal_data.email_hint': 'Inserisci la tua email',
  'personal_data.phone_hint': 'Inserisci il tuo numero',
  'personal_data.business_section': 'Dati aziendali',
  'personal_data.business_section_desc':
      'I dati dell\'azienda per cui hai attivato l\'account business.',
  'personal_data.job_role': 'Ruolo aziendale',
  'personal_data.job_role_hint': 'Seleziona il tuo ruolo',
  'personal_data.company_name': 'Nome dell\'Azienda',
  'personal_data.company_name_hint': 'Inserisci il nome dell\'azienda',
  'personal_data.vat': 'Partita IVA',
  'personal_data.vat_hint': '11 cifre, senza spazi',
  'personal_data.vat_invalid': 'Inserisci una Partita IVA valida: 11 cifre, di cui l\'ultima deve corrispondere alle altre.',
  'personal_data.tax_code_invalid': 'Inserisci un Codice Fiscale valido: 16 caratteri, di cui l\'ultimo deve corrispondere agli altri.',
  'personal_data.vat_taken': 'Questa partita IVA è già registrata su un altro account',
  'personal_data.tax_code_hint': 'Inserisci il codice fiscale',
  // Su un account business il codice fiscale è quello del titolare, mentre la
  // Partita IVA identifica l'azienda: due parti diverse, due identificativi.
  'personal_data.owner_tax_code': 'Codice Fiscale del titolare',
  'personal_data.owner_tax_code_hint':
      'Inserisci il Codice Fiscale del titolare',
  'personal_data.pec': 'PEC (posta certificata)',
  'personal_data.pec_hint': 'es. azienda@pec.it',
  'personal_data.save_changes': 'Salva Modifiche',
  'personal_data.cancel_discard': 'Annulla e scarta',
  'personal_data.update_success_title': 'Profilo Aggiornato',
  'personal_data.update_success_message': 'Il tuo profilo è stato aggiornato con successo.',
  'personal_data.update_error_title': 'Aggiornamento Fallito',
  'personal_data.update_error_message': 'Si è verificato un errore durante l\'aggiornamento del profilo. Riprova.',

  // ==================== SELECT UTILITY ====================
  'select_utility.title': 'Seleziona Utenza',
  'select_utility.heading': 'Quali utenze vuoi\nottimizzare?',
  'select_utility.subtitle': 'Seleziona il servizio per cui vuoi trovare le migliori offerte',
  'select_utility.luce_sublabel': 'Ottimizza la tua bolletta elettrica',
  'select_utility.gas_sublabel': 'Riduci le tue spese del gas',
  'select_utility.tip_label': 'Consiglio: ',
  'select_utility.tip_text': 'Puoi caricare altre bollette in seguito per confrontare tutte le tue utenze.',

  // ==================== UPLOAD BILL ====================
  'upload_bill.appbar_title': 'Carica la tua bolletta',
  'upload_bill.heading_electricity': 'Carica la tua bolletta luce',
  'upload_bill.heading_gas': 'Carica la tua bolletta di gas',
  'upload_bill.subtitle': 'Scegli il metodo più comodo per te',
  'upload_bill.info_text': 'Ci serve la tua bolletta per analizzare la tua offerta attuale e verificare se ci sono alternative più convenienti.',
  'upload_bill.info_link': 'Perché ne abbiamo bisogno?',
  'upload_bill.info_popup_title': 'Perché abbiamo bisogno della tua bolletta?',
  'upload_bill.info_popup_body': 'La tua bolletta contiene dettagli essenziali sul tuo piano energetico attuale, come i consumi, i prezzi e le condizioni contrattuali.\n\nAnalizzando queste informazioni, possiamo confrontare accuratamente il tuo piano attuale con le offerte disponibili sul mercato e suggerirti alternative che potrebbero farti risparmiare.\n\nSenza la tua bolletta, non saremmo in grado di fornirti raccomandazioni personalizzate basate sul tuo consumo reale.',
  'upload_bill.info_popup_close': 'Ho capito',
  'upload_bill.upload_file': 'Carica un file',
  'upload_bill.upload_formats': 'PDF o foto',
  'upload_bill.scan_file': 'Scatta una foto',
  'upload_bill.scan_use_camera': 'Fotografa la bolletta',
  'upload_bill.or_divider': 'OPPURE',
  'upload_bill.send_email': 'Invia via email',
  'upload_bill.send_email_address': 'Inoltra a @email',
  'upload_bill.looking_for_title': 'Cosa analizziamo dalla bolletta',
  'upload_bill.looking_for_1': 'Fornitore e offerta attuale',
  'upload_bill.looking_for_2': 'Consumo annuo',
  'upload_bill.looking_for_3': 'Prezzo dell’energia e costi fissi',
  'upload_bill.looking_for_4': 'Indirizzo di fornitura',
  'upload_bill.scanner_title': 'Scansiona la tua bolletta',
  'upload_bill.scanner_hint': 'Allinea la tua bolletta nella cornice',
  'upload_bill.uploading': 'Caricamento in corso...',
  'upload_bill.upload_success': 'Bolletta caricata con successo!',
  'upload_bill.upload_failed': 'Caricamento fallito. Riprova.',
  'upload_bill.file_too_large': 'File troppo grande. Massimo 10 MB.',
  'upload_bill.invalid_file_type': 'Tipo di file non valido. Usa PDF, JPG o PNG.',
  'upload_bill.select_source': 'Seleziona sorgente',
  'upload_bill.photo_gallery': 'Foto dalla galleria',
  'upload_bill.pdf_document': 'Documento PDF',
  'upload_bill.take_photo': 'Scatta foto',
  'upload_bill.upload_button': 'Carica la bolletta',
  'upload_bill.remove_file': 'Rimuovi',
  'upload_bill.extracting': 'Analisi bolletta in corso...',
  'upload_bill.extraction_complete': 'Dati estratti dalla bolletta',
  'upload_bill.extraction_verify': 'Verifica i dati estratti prima di caricare.',
  'upload_bill.extraction_failed': 'Impossibile leggere la bolletta. Riprova con una foto più chiara.',
  'upload_bill.extraction_no_data': 'Nessun dato trovato nella bolletta. Riprova con una foto più chiara.',
  'upload_bill.extraction_missing_fields': 'Alcuni dati obbligatori non sono stati trovati',
  'upload_bill.extraction_retry_hint': 'Riprova con una foto più chiara o un PDF leggibile.',
  'upload_bill.field_supplier': 'Fornitore',
  'upload_bill.field_pod': 'POD',
  'upload_bill.field_pdr': 'PDR',
  'upload_bill.field_total': 'Importo totale',
  'upload_bill.field_consumption': 'Consumo',
  'upload_bill.field_cost_per_unit': 'Costo unitario',
  'upload_bill.field_fixed_charges': 'Quota fissa',
  'upload_bill.field_taxes': 'Imposte',
  'upload_bill.field_period': 'Periodo',
  'upload_bill.field_address': 'Indirizzo fornitura',
  'upload_bill.field_tax_code': 'Codice Fiscale',
  'upload_bill.field_vat': 'Partita IVA',
  'upload_bill.field_contract': 'N. Contratto',
  'upload_bill.field_meter': 'Matricola contatore',
  'upload_bill.field_customer': 'Intestatario',

  // Caricamento multi-file
  'upload_bill.files_selected': '@count file selezionati',
  'upload_bill.clear_all': 'Rimuovi tutti',
  'upload_bill.add_more_files': 'Aggiungi altri file',
  'upload_bill.no_files_selected': 'Nessun file selezionato',
  'upload_bill.tap_to_select': 'Tocca Carica File per iniziare',
  'upload_bill.upload_x_files': 'Carica @count file',
  'upload_bill.uploading_progress': 'Caricamento @current di @total file',
  'upload_bill.cancel': 'Annulla',
  'upload_bill.batch_complete': 'Completato: @uploaded caricati, @failed falliti',
  'upload_bill.retry_failed': 'Riprova falliti',
  'upload_bill.done': 'Fatto',
  'upload_bill.max_files_reached': 'Massimo 10 file già selezionati.',
  'upload_bill.file_card': 'File',
  'upload_bill.retry_file': 'Riprova caricamento',
  'upload_bill.status_pending': 'In attesa',
  'upload_bill.status_extracting': 'Analisi...',
  'upload_bill.status_extracted': 'Pronto',
  'upload_bill.status_uploading': 'Caricamento',
  'upload_bill.status_uploaded': 'Caricato',
  'upload_bill.status_failed': 'Fallito',
  'upload_bill.file_validation_title': 'Selezione file',
  'upload_bill.skipped_duplicates': 'Duplicati saltati: @files',
  'upload_bill.skipped_invalid': 'File non supportati: @files',
  'upload_bill.skipped_oversized': 'Troppo grandi: @files (max 10 MB)',
  'upload_bill.skipped_over_limit': '@count file saltati: massimo 10 file',
  'upload_bill.error_network': 'Errore di rete. Controlla la connessione.',
  'upload_bill.error_timeout': 'Richiesta scaduta. Riprova.',
  'upload_bill.error_server': 'Errore del server. Riprova più tardi.',
  'upload_bill.error_file_access': 'Impossibile accedere al file. Potrebbe non essere più disponibile.',
  'upload_bill.error_storage_access': 'Errore di accesso allo storage. Riprova.',
  'upload_bill.permission_required_title': 'Permesso necessario',
  'upload_bill.permission_required_message': 'Il permesso di accesso allo storage è necessario per selezionare i file.',
  'upload_bill.open_settings': 'Impostazioni',
  'upload_bill.take_another_photo': 'Scatta un\'altra foto',
  'upload_bill.camera_title': 'Scansiona le tue bollette',
  'upload_bill.camera_done': 'Fatto',
  'upload_bill.camera_initializing': 'Avvio fotocamera...',
  'upload_bill.camera_error': 'Impossibile avviare la fotocamera. Controlla i permessi.',
  'upload_bill.camera_limit_reached': 'Numero massimo di foto raggiunto',
  'upload_bill.camera_discard_title': 'Eliminare le foto?',
  'upload_bill.camera_discard_message': 'Hai @count foto. Vuoi eliminarle?',
  'upload_bill.camera_discard_yes': 'Elimina',
  'upload_bill.camera_discard_no': 'Continua a scattare',

  'sign_contract.appbar_title': 'Firma il tuo Contratto',
  'sign_contract.action_required': 'Azione Richiesta',
  'sign_contract.ready_title': 'Pronto da Firmare',
  'sign_contract.ready_desc': 'Il tuo contratto è pronto! Firmalo per completare il tuo passaggio a @supplier.',
  'sign_contract.ready_desc_generic': 'Il tuo contratto è pronto! Firmalo per completare il tuo passaggio.',
  'sign_contract.pill_active': 'Attivo',
  'sign_contract.active_title': 'Contratto Attivo',
  'sign_contract.active_desc': 'La tua nuova fornitura è attiva. La trovi nella sezione Le mie Utenze.',
  'sign_contract.pill_in_activation': 'In Attivazione',
  'sign_contract.in_activation_title': 'Utenza in Attivazione',
  'sign_contract.in_activation_desc': 'Il passaggio al nuovo fornitore è in corso. La trovi già nella sezione Le mie Utenze e ti avviseremo appena sarà attiva.',
  'sign_contract.closed_title': 'Contratto Chiuso',
  'sign_contract.closed_desc': 'Questo contratto non è più attivo. Contatta l\'assistenza se hai bisogno di aiuto.',
  'sign_contract.pill_preparing': 'In Preparazione',
  'sign_contract.preparing_title': 'Contratto in Preparazione',
  'sign_contract.preparing_desc': 'Stiamo preparando il tuo contratto. Ti avviseremo appena sarà pronto da firmare.',
  'sign_contract.supplier_label': 'Fornitore',
  'sign_contract.offer_name_label': 'Nome Offerta',
  'sign_contract.activation_date_label': 'Data di Attivazione',
  'sign_contract.savings_label': 'Risparmio Annuo Stimato',
  'sign_contract.savings_suffix': '/anno',
  'sign_contract.error_load': 'Impossibile caricare il tuo contratto.',
  'sign_contract.error_missing_bill': 'Contratto non trovato.',
  'sign_contract.view_tutorial': 'Visualizza Tutorial di Firma',

  // ==================== BUSINESS JOB ROLES ====================
  'business_role.ceo': 'CEO / Fondatore',
  'business_role.manager': 'Manager',
  'business_role.finance': 'Responsabile Finanziario',
  'business_role.it': 'Amministratore IT',
  'business_role.other': 'Altro',

  // ==================== TERMS & CONDITIONS ====================
  'terms.title': 'Termini e Condizioni',

  // ==================== AGREEMENTS ====================
  'agreements.how_to_1': 'Copia il tuo codice sconto usando il pulsante in alto',
  'agreements.how_to_2': 'Visita il sito del partner: ',
  'agreements.how_to_3': 'Mostra il codice in negozio, oppure inseriscilo al pagamento se ordini online',
  'agreements.how_to_4': 'Goditi il tuo sconto esclusivo!',

  // ==================== OFFER DETAILS EXTRA STRINGS ====================
  'offer.details_title': 'Dettagli Offerta',
  'offer.price_type_link': 'Cosa significa?',
  // Offerte indicizzate / variabili: il prezzo segue un indice di mercato, che
  // è il PUN GME per la luce e il PSV per il gas — da qui il parametro.
  'offer.price_type_indexed_title': 'Prezzo indicizzato: come funziona?',
  'offer.price_type_indexed_text': "Il prezzo dell'energia varia seguendo l'andamento del mercato all'ingrosso, rappresentato dal @index.",
  'offer.price_type_indexed_note': 'Il costo può aumentare o diminuire nel tempo in base alle variazioni del mercato.',
  // Offerte a prezzo fisso: nessun riferimento a PUN, indicizzazione o spread.
  'offer.price_type_fixed_title': 'Prezzo fisso: cosa significa?',
  'offer.price_type_fixed_text': "Il prezzo dell'energia resta lo stesso per tutto il periodo contrattuale indicato nell'offerta, indipendentemente dalle oscillazioni del mercato all'ingrosso.",
  'offer.price_type_fixed_note': 'Sai fin da subito quanto pagherai: il costo non cambia se il mercato sale.',
  'offer.energy_price_link': 'Come viene calcolato?',
  'offer.price_calc_title': 'Calcolo del Prezzo',
  'offer.price_calc_subtitle': 'Il prezzo è calcolato come:',
  'offer.price_calc_footer': 'Questa formula trasparente segue\nl\'indice ufficiale del mercato energetico.',
  'offer.max_benefit': 'RISPARMIO ANNUO STIMATO',
  'offer.estimated_savings': 'RISPARMIO STIMATO',
  'offer.economic_conditions': 'Condizioni economiche',
  'offer.economic_conditions_unavailable': 'Documento non ancora disponibile',

  // Document Viewer
  'document_viewer.loading': 'Caricamento documento...',
  'document_viewer.error': 'Impossibile caricare il documento',
  'document_viewer.save_error_title': 'Errore',
  'document_viewer.save_error_message': 'Impossibile salvare il documento',
  'document_viewer.unsupported':
      'Questo tipo di file non può essere visualizzato nell\'app.',
  'document_viewer.open_external': 'Apri fuori dall\'app',
  'document_viewer.open_external_error':
      'Nessuna app su questo dispositivo può aprire questo file.',

  'offer.select_offer': 'Seleziona questa Offerta',

  // ==================== AUTH VALIDATION ====================
  'auth.validation.error': 'Errore',
  'auth.validation.warning': 'Attenzione',
  'auth.validation.success': 'Successo',
  'auth.validation.info': 'Info',
  'auth.reset_password.empty_error': 'Inserisci le password',
  'auth.reset_password.min_length_error': 'La password deve essere almeno 8 caratteri',
  'auth.reset_password.lowercase_error': 'La password deve contenere almeno una lettera minuscola',
  'auth.reset_password.uppercase_error': 'La password deve contenere almeno una lettera maiuscola',
  'auth.reset_password.number_error': 'La password deve contenere almeno un numero',
  'auth.reset_password.special_char_error': 'La password deve contenere almeno un carattere speciale',
  'auth.reset_password.success_message': 'Password reimpostata',
  'auth.reset_password.failed_error': 'Impossibile reimpostare la password',
  'auth.otp.verified_success': 'Codice verificato',
  'auth.otp.verification_failed': 'Verifica del codice non riuscita',
  'auth.otp.resend_title': 'Codice richiesto',
  'auth.otp.resend_message': 'Se l’indirizzo email è registrato e richiede la verifica, abbiamo inviato un nuovo codice.',
  'auth.forgot_password.otp_sent_success': 'Se l’indirizzo email è registrato, abbiamo inviato un codice per reimpostare la password.',
  'auth.forgot_password.send_failed_error': 'Non riusciamo a inviare il codice in questo momento. Riprova tra poco.',
  'auth.signup.registration_failed_default': 'Registrazione fallita. Riprova.',
  'auth.signup.password_requirements_unmet': 'La password non soddisfa i requisiti di sicurezza',
  'auth.session_expired.title': 'Sessione Scaduta',
  'auth.session_expired.message': 'La tua sessione è scaduta. Accedi di nuovo.',

  // ==================== FAQ ====================
  'faq.title': 'Domande Frequenti',
  'faq.error': 'Qualcosa è andato storto. Riprova.',
  'faq.retry': 'Riprova',
  'faq.empty': 'Nessuna FAQ disponibile al momento.',

  // ==================== REQUEST DETAILS ====================
  'request.details.title': 'Dettagli Richiesta',
  'request.details.processing_title': 'Elaborazione della tua Richiesta',
  'request.details.processing_desc': 'Stiamo lavorando al tuo passaggio. Nessuna azione\nrichiesta da parte tua al momento.',
  'request.details.submission_date': 'Data di invio',
  'request.details.in_analysis': 'In analisi',
  'request.details.info_message': 'La verifica viene completata generalmente entro 24 ore lavorative. Ti aggiorneremo non appena sarà terminata.',

  // ==================== BILLS FILTERS ====================
  'bills.filter.bill_type': 'Tipo di Bolletta:',
  'bills.filter.all_types': 'Tutte',
  'bills.filter.electricity': 'Elettricita',
  'bills.filter.gas': 'Gas',
  'bills.filter.status': 'Stato:',
  'bills.filter.all_statuses': 'Tutti',
  'bills.filter.uploaded': 'Caricata',
  'bills.filter.analyzing': 'In analisi',
  'bills.filter.analyzed': 'Analizzata',
  'bills.filter.error': 'Errore',
  'bills.list.your_bills': 'Le Tue Bollette',
  'bills.list.found': 'trovate',
  'bills.list.page_of': 'Pagina @current di @total',

  // ==================== BILL DETAIL LABELS ====================
  'bills.detail.bill_type': 'Tipo di Bolletta',
  'bills.detail.status': 'Stato',
  'bills.detail.pod_number': 'Numero POD',
  'bills.detail.pdr_number': 'Numero PDR',
  'bills.detail.billing_period': 'Periodo di fatturazione',
  'bills.detail.total_amount': 'Importo Totale',
  'bills.detail.consumption': 'Consumo',
  'bills.detail.cost_per_unit': 'Costo per Unita',
  'bills.detail.fixed_charges': 'Costi Fissi',
  'bills.detail.taxes': 'Tasse',
  'bills.detail.supply_address': 'Indirizzo di fornitura',
  'bills.detail.codice_fiscale': 'Codice Fiscale',
  'bills.detail.partita_iva': 'Partita IVA',
  'bills.detail.contract_number': 'N. Contratto',
  'bills.detail.meter_number': 'Matricola Contatore',
  'bills.detail.customer_name': 'Intestatario',
  'bills.detail.status_pending_email': 'Il nostro team sta verificando la tua bolletta, il processo richiederà 7 giorni lavorativi',
  'bills.detail.status_uploaded': 'Bolletta caricata, in attesa di analisi',
  'bills.detail.status_analyzing': 'Analisi in corso...',
  'bills.detail.status_analyzed': 'Analisi completata',
  'bills.detail.status_error': 'Errore durante l\'analisi',
  'bills.detail.status_verification_required': 'Verifica richiesta — invia i documenti richiesti',
  'bills.detail.status_verification_review': 'Il nostro team sta verificando i dati della tua bolletta',
  'bills.detail.status_verified': 'I dati della tua bolletta sono stati verificati',
  'bills.detail.status_offer_accepted': 'Hai accettato un\'offerta. Stiamo preparando il contratto.',
  'bills.detail.status_awaiting_activation': 'La tua fornitura è in attivazione',
  'bills.detail.potential_savings': 'RISPARMIO POTENZIALE',
  'bills.detail.estimated_annual': 'Risparmio Annuale Stimato',

  // ==================== BILL MODEL DISPLAY ====================
  'bills.type.electricity': 'Luce',
  'bills.type.gas': 'Gas',
  'bills.status.pending_email': 'In attesa (Email)',
  'bills.status.uploaded': 'Caricata',
  'bills.status.analyzing': 'In analisi',
  'bills.status.analyzed': 'Analizzata',
  'bills.status.error': 'Errore',
  'bills.status.verification_required': 'Verifica richiesta',
  'bills.status.verification_review': 'In analisi',
  'bills.status.verified': 'Verificata',
  'bills.status.offer_sent': 'Offerte inviate',
  'bills.status.offer_accepted': 'Offerta accettata',
  'bills.status.case_created': 'Pratica creata',
  'bills.status.contract_sent': 'Contratto inviato',
  'bills.status.awaiting_activation': 'In attivazione',
  'bills.status.activated': 'Attivata',
  'bills.status.cancelled': 'Annullata',
  'bills.supplier.unknown': 'Fornitore sconosciuto',
  'bills.period.from': 'Dal',

  // ==================== ONBOARDING ====================
  'onboarding.question': 'Come vuoi usare VYZI?',
  'onboarding.subtitle': 'Scegli il tipo di account',
  'onboarding.private': 'Privato',
  'onboarding.private_desc': 'Per uso personale e per le utenze di casa',
  'onboarding.business': 'Azienda',
  'onboarding.business_desc': 'Per aziende e professionisti con Partita IVA',
  'onboarding.private_point1': 'Gestisci le utenze luce e gas di casa',
  'onboarding.private_point2': 'Confronta le offerte disponibili',
  'onboarding.private_point3': 'Monitora consumi e risparmio',
  'onboarding.business_point1': 'Gestisci più utenze aziendali',
  'onboarding.business_point2': 'Confronta offerte luce e gas per la tua attività',
  'onboarding.business_point3': 'Gestisci Partita IVA e dati aziendali',
  'onboarding.sign_in': 'Accedi',
  'onboarding.create_account': 'Crea un account',

  // ==================== REQUEST OFFERS ====================
  'request.filter.payment_method': 'Metodo di Pagamento:',
  'request.filter.all': 'Tutti',
  'request.filter.direct_debit': 'Addebito Diretto',
  'request.filter.postal_slip': 'Bollettino Postale',
  'request.offers.payment_method_label': 'Metodo di Pagamento',
  'request.offers.none_for_payment_method':
      'Nessuna offerta accetta questo metodo di pagamento.\nProva un altro filtro.',
  'request.offers.best_for_you': 'Migliori Offerte per Te',
  'request.offers.found': 'trovate',
  'request.offers.energy_price_fixed': 'Prezzo Energia (Fisso): @price',
  'request.offers.energy_price_indexed': 'Prezzo Energia: @index + @spread',
  'request.offers.energy_price_spread': 'Spread',
  'request.offers.estimated_savings': 'Risparmio annuale stimato',
  'request.offers.empty_title': 'Le tue offerte, sotto controllo',
  'request.offers.empty_desc': 'Analizziamo la tua bolletta e verifichiamo se ci sono offerte più convenienti per te.',
  'request.offers.view_details': 'Visualizza Dettagli',
  'request.offers.amount_label': 'Importo',
  // Shown when a "new offers" notification narrowed the list to one request.
  'request.offers.for_request': 'Offerte per @supply',
  'request.offers.for_this_request': 'Offerte per questa richiesta',
  'request.offers.show_all': 'Mostra tutte',
  'request.offers.none_for_request':
      'Non ci sono ancora offerte per questa richiesta.\nTi avviseremo appena saranno disponibili.',

  // ==================== AGREEMENTS ====================
  'agreements.title': 'Convenzioni',
  'agreements.subtitle': 'Sconti esclusivi per te',
  'agreements.your_benefits': 'I Tuoi Vantaggi',
  'agreements.benefits_desc': 'Goditi sconti esclusivi presso i nostri ristoranti partner come membro prezioso.',
  'agreements.details_title': 'Dettagli Convenzione',
  'agreements.offer_date': 'Data Offerta: ',
  'agreements.exclusive_discount': 'Il Tuo Sconto Esclusivo',
  'agreements.discount_code': 'Codice Sconto',
  'agreements.copied': 'Copiato!',
  'agreements.copy': 'Copia',
  'agreements.location': 'Posizione',
  'agreements.open_maps': 'Apri in Google Maps',
  'agreements.how_to_use': 'Come Usare il Tuo Sconto',
  'agreements.no_agreements': 'Nessuna convenzione disponibile al momento',
  'agreements.error_loading': 'Impossibile caricare le convenzioni',
  'agreements.retry': 'Riprova',

  // ==================== STATIC PAGES ====================
  'static_page.loading': 'Caricamento...',
  'static_page.error': 'Impossibile caricare il contenuto. Riprova più tardi.',
  'static_page.not_available': 'Questo contenuto non è ancora disponibile. Riprova più tardi.',
  'static_page.retry': 'Riprova',

  // ==================== DOCUMENTI LEGALI E CONSENSI ====================
  'legal.version': 'Versione',
  'legal.updated_on': 'Aggiornato il',
  'legal.accepted_on': 'Hai accettato la versione @version il @date.',
  'legal.pending_update': 'Hai accettato la versione @accepted. Ora è in vigore la versione @current e serve la tua approvazione.',
  'legal.not_yet_accepted': 'Non hai ancora accettato questo documento.',
  'legal.gate_title': 'Leggi e accetta',
  'legal.step': 'Passo @current di @total',
  'legal.whats_changed': 'COSA È CAMBIATO',
  'legal.replaces_version': 'sostituisce la versione @version',
  'legal.scroll_to_end': 'Scorri fino in fondo per continuare',
  'legal.accept_checkbox': 'Ho letto e accetto @title (versione @version).',
  'legal.accept_and_continue': 'Accetta e continua',
  'legal.accept_and_next': 'Accetta e continua',
  'legal.logout': 'Esci',
  'legal.decline_title': 'Continuare senza accettare?',
  'legal.decline_body': 'Per continuare a usare EasyRisparmio devi accettare i documenti aggiornati. Verrai disconnesso e potrai accettarli al prossimo accesso.',
  'legal.decline_cancel': 'Torna indietro',
  'legal.decline_confirm': 'Esci',
  'legal.accept_failed': 'Non è stato possibile registrare la tua accettazione. Riprova.',
  'legal.version_changed': 'È appena stata pubblicata una nuova versione. La stiamo caricando...',

  // ==================== CASE / PRATICA ====================
  'case.status.new': 'Nuova richiesta',
  'case.status.in_progress': 'In lavorazione',
  'case.status.documents_pending': 'Documenti richiesti',
  'case.status.contract_sent': 'Contratto inviato',
  'case.status.awaiting_activation': 'Utenza in attivazione',
  'case.status.activated': 'Utenza attivata',
  'case.status.rejected': 'Richiesta rifiutata',
  'case.status.cancelled': 'Richiesta annullata',

  'case.step.sent': 'Inviata',
  'case.step.in_progress': 'In Lavorazione',
  'case.step.contract': 'Contratto',
  'case.step.signed': 'Firmato',
  'case.step.active': 'Attiva',
  'case.step.contract_sent': 'Contratto Inviato',
  'case.step.activated': 'Attivata',

  'case.detail.title': 'Dettagli Pratica',
  'case.detail.pratica': 'Pratica',
  'case.detail.details_button': 'Dettagli Pratica',
  'case.detail.error.not_found': 'ID pratica non trovato',
  'case.detail.error.load_failed': 'Impossibile caricare i dati',
  'case.detail.error.connection': 'Errore di connessione',
  'case.detail.selected_offer': 'Offerta selezionata',
  'case.detail.contract': 'Contratto',
  'case.detail.contract_preparing': 'Contratto in preparazione',
  'case.detail.contract_preparing_desc': 'Il contratto ti verrà inviato a breve.',
  'case.detail.sent_via': 'Inviato',
  'case.detail.download_contract': 'Scarica Contratto',
  'case.detail.upload_signed': 'Carica Contratto Firmato',
  'case.detail.waiting_confirmation': 'In attesa di conferma dall\'operatore',
  'case.detail.utility_in_activation': 'Utenza in attivazione',
  'case.detail.utility_activated': 'Utenza attivata!',
  'case.detail.activated_on': 'Attivata il',
  'case.detail.upload_success': 'Contratto firmato caricato con successo',
  'case.detail.upload_error': 'Impossibile caricare il contratto firmato',
  'case.detail.contract_documents': 'Documenti del contratto',
  'case.detail.signed_documents': 'Documenti firmati',
  'case.detail.sign_guideline': 'Guida alla firma del contratto',

  // ==================== BILL STATUS MESSAGES ====================
  'bills.status_msg.offer_sent': 'Offerte disponibili',
  'bills.status_msg.case_created': 'Pratica in corso',
  'bills.status_msg.contract_sent': 'Contratto inviato',
  'bills.status_msg.activated': 'Utenza attivata',
  'bills.status_msg.cancelled': 'Pratica annullata',

  // ==================== NOTIFICHE ====================
  'notifications.title': 'Notifiche',
  'notifications.empty': 'Nessuna notifica',
  'notifications.mark_all_read': 'Segna tutto come letto',
  'notifications.all_read': 'Tutte le notifiche segnate come lette',
  'notifications.load_more': 'Carica altro',
  'notifications.type.bill_analyzed': 'Bolletta Analizzata',
  'notifications.type.bill_verification': 'Verifica Richiesta',
  'notifications.type.offer_available': 'Nuova Offerta',
  'notifications.type.case_update': 'Aggiornamento Pratica',
  'notifications.type.contract_status': 'Aggiornamento Contratto',
  'notifications.type.referral_status': 'Aggiornamento Referral',
  'notifications.type.contract_verification': 'Verifica Contratto',
  'notifications.type.activation_complete': 'Attivazione Completata',
  'notifications.type.support_reply': 'Risposta Supporto',
  'notifications.type.general': 'Generale',

  // ==================== BILL VERIFICATION ====================
  'verification.title': 'Verifica',
  'verification.admin_message_title': 'Messaggio dall\'Amministratore',
  'verification.upload_documents': 'Invia Documenti',
  'verification.upload_hint':
      'Carica un file o scatta una foto del documento richiesto.',
  'verification.your_message': 'Il tuo messaggio (facoltativo)',
  'verification.your_message_hint': 'Aggiungi altre informazioni...',
  'verification.submit': 'Invia Documento',
  'verification.file_required': 'Aggiungi almeno un documento',
  'verification.missing_documents_title': 'Nessun Documento',
  'verification.upload_retry':
      'Non è stato possibile caricare i documenti. Riprova.',
  'verification.submitted_title': 'Documenti Inviati',
  'verification.submitted_message':
      'I tuoi documenti sono stati inviati. Li esamineremo e ti ricontatteremo.',
  'verification.error_title': 'Errore',
  'verification.submit_failed': 'Invio non riuscito. Riprova.',
  'verification.load_failed': 'Impossibile caricare i dettagli della verifica',
  'verification.retry': 'Riprova',
  'verification.done': 'Fatto',
  'verification.none_pending': 'Nessuna verifica in sospeso',
  'verification.history_title': 'Cronologia Verifiche',
  'verification.round': 'Round @number',
  'verification.status_pending': 'IN ATTESA DI RISPOSTA',
  'verification.status_submitted': 'INVIATO',
  'verification.status_resolved': 'RISOLTO',
  'verification.type_bill': 'DOCUMENTO BOLLETTA',
  'verification.type_contract': 'CONTRATTO FIRMATO',
  'verification.admin_request': 'Richiesta Amministratore',
  'verification.your_response': 'La tua risposta',
  'verification.uploaded_files': 'File Caricati (@count)',
  'verification.no_details': 'Nessun documento inviato.',
  'verification.image_load_failed': 'Impossibile caricare l\'immagine',
  'home.email_bill.hero_title': 'Invia via email',
  'home.email_bill.hero_subtitle': 'Inoltra la tua bolletta all’indirizzo qui sotto.',
  'my_utility.empty_desc': 'Carica una bolletta per confrontare le offerte e richiedere l’attivazione di una nuova utenza.',
  'bills.detail.via_email': 'Via email',
  'offer.savings_comparison': 'Rispetto alla tua offerta attuale',
  'common.copied': 'Copiato',
  'home.email_bill.copied': 'Indirizzo email copiato negli appunti',
  'home.email_bill.failed': 'Non è stato possibile creare la richiesta. Riprova.',
  'system.password_reused': 'La nuova password deve essere diversa da quella attuale.',
  'system.current_password_incorrect': 'La password attuale non è corretta.',
  'system.email_registered': 'Questo indirizzo email è già registrato.',
  'system.code_expired': 'Il codice non è valido o è scaduto. Richiedi un nuovo codice.',
  'system.code_attempts': 'Troppi tentativi non riusciti. Richiedi un nuovo codice.',
  'system.unexpected': 'Si è verificato un errore. Riprova tra poco.',
  'system.validation': 'Controlla i dati inseriti e riprova.',
  'system.not_found': 'I dati richiesti non sono disponibili.',
  'system.forbidden': 'Non hai accesso a questa operazione.',
  'system.referral_invalid': 'Il codice di invito non è valido.',
  'system.referral_self': 'Non puoi utilizzare il tuo codice di invito.',
  'system.too_many_requests': 'Troppe richieste. Attendi un momento e riprova.',
  'common.ok': 'OK',
  'common.new': 'Nuovo',
  'referral.not_available_title': 'Invito non disponibile',
  'referral.not_available_message': 'Questo link di invito non può essere applicato perché hai già effettuato l’accesso. I premi per gli inviti sono riservati ai nuovi account creati tramite un link di invito.',
  'upload_bill.flash_auto': 'Auto',
  'upload_bill.flash_on': 'Attivo',
  'upload_bill.flash_off': 'Spento',
  'upload_bill.submitted_success': 'Bolletta inviata correttamente.',
  'validation.phone_invalid': 'Inserisci un numero di telefono valido',
  'support.hero_placeholder': 'Servizi per le utenze',
  'profile.member_since': 'Membro da @date',
  'duration.day_one': '1 giorno',
  'duration.days': '@count giorni',
  'duration.month_one': '1 mese',
  'duration.months': '@count mesi',
  'offer.duration_indefinite': 'Durata indeterminata',
  'offer.no_binding': 'Nessun vincolo',
  'offer.market_fixed': 'Prezzo fisso',
  'offer.market_variable': 'Prezzo variabile',
  'offer.market_indexed': 'Prezzo indicizzato',
  'request.form.target_business': 'Business',
  'request.form.target_residential': 'Residenziale',
  'request.form.documents_upload_failed': 'Non è stato possibile caricare uno o più documenti di identità. Riprova.',
  'agreements.valid_from': 'Dal @date',
  'notifications.channel_name': 'Notifiche VYZI',
  'notifications.channel_description': 'Aggiornamenti su bollette, offerte e richieste',
  'common.search': 'Cerca',
  'api_field.email': 'Email',
  'api_field.password': 'Password',
  'api_field.confirmPassword': 'Conferma password',
  'api_field.currentPassword': 'Password attuale',
  'api_field.newPassword': 'Nuova password',
  'api_field.firstName': 'Nome',
  'api_field.lastName': 'Cognome',
  'api_field.phone': 'Numero di telefono',
  'api_field.codiceFiscale': 'Codice fiscale',
  'api_field.partitaIva': 'Partita IVA',
  'api_field.companyName': 'Ragione sociale',
  'api_field.companyType': 'Tipo di società',
  'api_field.legalRepresentative': 'Legale rappresentante',
  'api_field.atecoCode': 'Codice ATECO',
  'api_field.jobRole': 'Ruolo',
  'api_field.pecEmail': 'PEC',
  'api_field.role': 'Tipo di account',
  'api_field.referralCode': 'Codice invito',
  'api_field.code': 'Codice di verifica',
  'api_field.acceptedTerms': 'Accettazione dei termini',
  'api_field.iban': 'IBAN',
  'api_field.ibanHolderFirstName': 'Nome dell’intestatario del conto',
  'api_field.ibanHolderLastName': 'Cognome dell’intestatario del conto',
  'api_field.ibanHolderTaxCode': 'Codice fiscale o partita IVA dell’intestatario',
  'api_field.podNumber': 'Codice POD',
  'api_field.pdrNumber': 'Codice PDR',
  'api_field.meterNumber': 'Numero contatore',
  'api_field.address': 'Indirizzo',
  'api_field.streetAddress': 'Indirizzo',
  'api_field.city': 'Comune',
  'api_field.province': 'Provincia',
  'api_field.postalCode': 'CAP',
  'api_field.country': 'Paese',
  'api_field.supplyStreet': 'Via di fornitura',
  'api_field.supplyStreetNumber': 'Numero civico di fornitura',
  'api_field.supplyCity': 'Comune di fornitura',
  'api_field.supplyProvince': 'Provincia di fornitura',
  'api_field.supplyPostalCode': 'CAP di fornitura',
  'api_field.residentialStreet': 'Via di residenza',
  'api_field.residentialStreetNumber': 'Numero civico di residenza',
  'api_field.residentialCity': 'Comune di residenza',
  'api_field.residentialProvince': 'Provincia di residenza',
  'api_field.residentialPostalCode': 'CAP di residenza',
  'api_field.shippingStreet': 'Via di spedizione',
  'api_field.shippingStreetNumber': 'Numero civico di spedizione',
  'api_field.shippingCity': 'Comune di spedizione',
  'api_field.shippingProvince': 'Provincia di spedizione',
  'api_field.shippingPostalCode': 'CAP di spedizione',
  'api_field.invoiceEmail': 'Email per la fattura',
  'api_field.paymentMethod': 'Metodo di pagamento',
  'api_field.invoiceDelivery': 'Invio della fattura',
  'api_field.language': 'Lingua',
  'api_field.contactPreference': 'Preferenza di contatto',
  'api_field.subject': 'Oggetto',
  'api_field.message': 'Messaggio',
  'api_field.description': 'Descrizione',
  'api_field.topicId': 'Argomento',
  'api_field.billType': 'Tipo di bolletta',
  'api_field.utilityType': 'Tipo di utenza',
  'api_field.documentType': 'Tipo di documento',
  'api_field.fileIds': 'Documenti',
  'api_field.offerId': 'Offerta',
  'api_field.selectedOfferId': 'Offerta',
  'api_field.notes': 'Note',
};
